### ISSUE TITLE
Chart-Parallel Coordinates:  Demo updates needed.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#100]
1. On demo page load, getting 404's on font-aweome, colors, and polyfill. (Happens on Chrome and Safari 9, but not on IE11, and FF)

2. In Safari9, when prevent resize is on, register is overlaying the chart.

3. In FF, register is never visible even if the prevent-resize option is turned off.

4. Just to clean up, should remove the "update" console log message on axis brush updates coming from multi-axis.html.  Same issue in Radar Chart.

### 404's on page load:
![screen shot 2017-07-31 at 1 21 59 pm](https://user-images.githubusercontent.com/10835611/28796656-404f279c-75f3-11e7-8782-566a0478283b.png)

### Safari9 with prevent resize on:
![screen shot 2017-07-31 at 1 24 06 pm](https://user-images.githubusercontent.com/10835611/28796776-b20161ca-75f3-11e7-897f-e4ba53b2f894.png)

### FF no register with prevent-resize off:
![screen shot 2017-07-31 at 1 20 49 pm](https://user-images.githubusercontent.com/10835611/28796806-c709b0fe-75f3-11e7-8b89-ddaf7495b584.png)

### Update console log:
![screen shot 2017-07-31 at 1 32 47 pm](https://user-images.githubusercontent.com/10835611/28797081-d8612548-75f4-11e7-97bf-2c7ad66fc48c.png)

**Comment by benoitjchevalier** [comment]
1. fixed
2. need to be looked at
3. actual demo resize issue, fixed
4. I updated vis but didn't release a new version as low priority

**Comment by nonmetalhail** [comment]
fixed 2 across all charts
