### ISSUE TITLE
Radar/Demo: issues with 404's on colors, font-awesome, polyfill and resize not working.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#104]
1. 404's on color, font awesome, and polyfill on page load for the radar demo (Seen in Chrome, Safari9)
2. Prevent resize toggle doesn't seem to trigger proper resizing to fit the container in Chrome and FF, (It works in Safari9 and IE11 for whatever reason!)

### 404's:
![screen shot 2017-07-31 at 3 29 25 pm](https://user-images.githubusercontent.com/10835611/28801215-570956d0-7605-11e7-836f-5fdf6a25c192.png)

### Resize in Chrome
![screen shot 2017-07-31 at 3 34 08 pm](https://user-images.githubusercontent.com/10835611/28801311-cda765de-7605-11e7-9899-b147e5c302c0.png)

**Comment by benoitjchevalier** [comment]
Should all be fixed in latests radar v1.0.1
