### ISSUE TITLE
Spark: Codepen fails to load spark with web worker failures.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#105]
Codepen for spark is failing, not able to find px-vis wek worker files.

## Screenshot:

![screen shot 2017-07-31 at 4 01 24 pm](https://user-images.githubusercontent.com/10835611/28802109-b280b0fe-7609-11e7-8f90-9e8c3bbd076b.png)

**Comment by randyaskin** [comment]
Works on my machine, but all of the vis components include this service worker error on CodePen.

**Comment by benoitjchevalier** [comment]
It's not a service worker but the actual vis webworker it's complaining about. For some it won't matter (spark) for other it actually will (timeseries). We are thinking of migrating the more advanced vis components to use Glitch instead of codepen
