### ISSUE TITLE
Broken Link on Additional Resources page - Predix UI Overview (P1)

### ISSUE THREAD

**Issue by Aileen-H** [predix-ui/predix-ui.github.io#109]
Under "Tutorials" - broken link to Predix UI overview on Predix.IO

https://docs.predix.io/en-US/content/platform/web_application_development/predix_ui/predix-ui-overview is NOT FOUND

NOTE: PRedix IO recent changes to change "Predix UI" to "Predix Design System"

**Comment by Aileen-H** [comment]
Also other links to Predix.IO pages are now broken:

https://docs.predix.io/en-US/content/platform/web_application_development/predix_ui/example-theme-web-applications-with-predix-ui#task_n4l_jnc_yv

**Comment by nonmetalhail** [comment]
Ken fixing
