### ISSUE TITLE
Timeseries: Colors.html is 404'ng on page load.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#110]
On demo page load, getting a 404 on colors.html in Chrome and safari9.

## Screenshot:

![screen shot 2017-07-31 at 4 24 04 pm](https://user-images.githubusercontent.com/10835611/28802687-b3ccd804-760c-11e7-9f8b-c74f720d716a.png)

**Comment by benoitjchevalier** [comment]
fixed in 3.0.2
