### ISSUE TITLE
Timeseries: Make timeseries great again (in IE11)...

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#111]
On IE11/laptop screen: Timeseries demo looks so sad on the win7 laptop (no external monitor) when prevent-resize is set.  Can we make it look good again? 

Properties container looks too wide, maybe readjusts the width to make more room for the main demo container? or force the side nav to close when the demo is loaded?

## Screenshot:

![2017-07-31_1621](https://user-images.githubusercontent.com/10835611/28802853-93a92ca2-760d-11e7-9220-857f62dcabf3.png)

**Comment by nonmetalhail** [comment]
I'm @nonmetalhail and I approve this message.

**Comment by benoitjchevalier** [comment]
Moved the register to horizontal by default
