### ISSUE TITLE
Percent-circle:  dark-theme-styles warnings on page load and codepen odd size rendering.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#116]
1. Warnings on missing dark-theme styles (but dark theme works fine).

![screen shot 2017-07-31 at 5 22 09 pm](https://user-images.githubusercontent.com/10835611/28803973-0be1f6b6-7615-11e7-84c0-1de672512f55.png)

2. Codepen rendering of the percent circle is huge? Not sure if this is intentional but looks odd.

![screen shot 2017-07-31 at 5 25 30 pm](https://user-images.githubusercontent.com/10835611/28803999-44bd7ae6-7615-11e7-9754-d58bb2f01d94.png)

**Comment by randyaskin** [comment]
Fixed in v1.0.1.
