### ISSUE TITLE
gauge:  Demo has minor inconsistencies across browsers.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#117]
#1:  IE11 only:
None of the properties' fields get populated with the gauge values in IE11.
Also the spin button never renders in IE11.  Only way to increase values is to enter them manually.

#2: Another inconsistency:
In Chrome:  spin buttons render on hover over.
In FF and Safari9: they are always present.

#3: Warnings in FF about not finding dark-theme:

### IE11:

![2017-07-31_1733](https://user-images.githubusercontent.com/10835611/28804350-6d3b9cd0-7617-11e7-8765-dba181353bd2.png)

### Chrome vs. FF:
![screen shot 2017-07-31 at 5 41 37 pm](https://user-images.githubusercontent.com/10835611/28804379-a78e1962-7617-11e7-9695-c977749242ec.png)

### FF Warnings on page load:
![screen shot 2017-07-31 at 5 44 07 pm](https://user-images.githubusercontent.com/10835611/28804427-f79e6eca-7617-11e7-870b-c0863586afbe.png)

**Comment by randyaskin** [comment]
What you refer to as "spin buttons" are simply style differences with how the various browsers render a native `<input type=number>` element - I don't think we have any control over that. Also, similar to #220, binding to input type number is not supported in IE11 per your first point above, so we may just want to switch to regular text inputs instead.

I don't see the dark theme errors in Firefox on my machine. ¯\_(ツ)_/¯

**Comment by randyaskin** [comment]
Switched to text inputs in v2.0.2.
