### ISSUE TITLE
Simple Area Chart & Simple Bar Chart: Toggle is missing ....

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#118]
Not sure if it's a build problem.

Toggle is 404'ng on page load for simple area chart.
It's missing from chrome and FF and in Safari9 and IE11 the old one is rendering for simple area chart.

### FF vs. Safari9 with 404 error:
![screen shot 2017-07-31 at 5 51 02 pm](https://user-images.githubusercontent.com/10835611/28804589-13f95ade-7619-11e7-85a6-bddb1db3b629.png)

**Comment by randyaskin** [comment]
Looks like a build problem. Still showing old toggle, old dropdown, no description, etc. Re-kicking build on Travis to see if that fixes it.

**Comment by randyaskin** [comment]
Simple bar chart looks right to me. Also doesn't include a toggle... can you clarify?

**Comment by ppeyro** [comment]
As of now: Simple Area Chart is still missing the toggle and 404'ng on toggle.html load.

Simple bar chart was throwing errors in IE11.  Not sure why d heck I lumped it together with this one... 
Here's a screenshot of the error:

![2017-07-31_1810](https://user-images.githubusercontent.com/10835611/28850506-df757860-76d1-11e7-8707-e397dd73ba80.png)

**Comment by benoitjchevalier** [comment]
can't see the error on IE for bar chart anymore, maybe fixed?

**Comment by randyaskin** [comment]
Built now.
