### ISSUE TITLE
 404's on font-awesome and catalog footer in a bunch of pages.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#119]
Martin saw this first, just logging the issue so we don't forget:

![screen shot 2017-07-31 at 5 56 33 pm](https://user-images.githubusercontent.com/10835611/28804681-a85ba4de-7619-11e7-82fc-e42b413e4240.png)

Here's the list of pages 404'ng on px-catalog-footer or font-awesome.html:

Designer Starter Kit
Under Design Guidelines:
All pages except Data visualization ( This one has a warning on px-theme-styles)

## Screenshots:

![screen shot 2017-07-31 at 5 56 33 pm](https://user-images.githubusercontent.com/10835611/28804766-2061ffe6-761a-11e7-95f7-26596c34055c.png)

![screen shot 2017-07-31 at 6 00 04 pm](https://user-images.githubusercontent.com/10835611/28804771-260340ae-761a-11e7-8c2b-2f72b715bb54.png)

**Comment by mdwragg** [comment]
On it

**Comment by nonmetalhail** [comment]
Just removed one from the XY demo

**Comment by mdwragg** [comment]
👍

**Comment by mdwragg** [comment]
Fixed by c0e99ccce6248e5ce42f66b8378ad9e9ef458d8e
