### ISSUE TITLE
Simple-area-chart: Description is missing.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#120]
The picture says a thousand words, but a few words in intro might not be bad either... :)

![screen shot 2017-07-31 at 6 03 39 pm](https://user-images.githubusercontent.com/10835611/28804848-b37b49cc-761a-11e7-8ca6-c653b1bf8578.png)

**Comment by benoitjchevalier** [comment]
if you're in there can you also remove the 2 console.warn?

**Comment by randyaskin** [comment]
There aren't any consoles in simple-area-chart... must be coming from one of your crazy behaviors?

**Comment by benoitjchevalier** [comment]
they're only in that old demo, not in the actual code, all good!

**Comment by benoitjchevalier** [comment]
description is actually included in the new demo, will be fixed when we figure why the demo isn't rebuilt: https://github.com/predix-ui/predix-ui.github.io/issues/118

**Comment by randyaskin** [comment]
Built now
