### ISSUE TITLE
Predix Design System wraps in site header

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#121]
Safari 10.1.2

Pipe separating Predix Developer Network and Predix Design System is too tall. Predix Design System wraps and increases the height of the header. Works correctly in Chrome.

![image](https://user-images.githubusercontent.com/25310251/28804853-c665d278-761a-11e7-8ef3-4f20bc29d206.png)

**Comment by benoitjchevalier** [comment]
fixed
