### ISSUE TITLE
Predix/Developer Network missing in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#123]
It took a while to notice this as my eyes glazed over....

In IE 11 only: the header is missing Predix Developer Network.

## Screenshot:
![2017-07-31_1842](https://user-images.githubusercontent.com/10835611/28805644-6695ced8-7620-11e7-8652-95cac64e047e.png)

**Comment by benoitjchevalier** [comment]
looking at it

**Comment by benoitjchevalier** [comment]
Fixed and centered
