### ISSUE TITLE
Simple-win-loss-chart:  Intro paragraph is incomplete?

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#124]
Doesn't look like the paragraph is complete.

![screen shot 2017-07-31 at 6 56 07 pm](https://user-images.githubusercontent.com/10835611/28805941-0fa92212-7622-11e7-87a5-fe74092e6430.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.1.
