### ISSUE TITLE
Data-table-column & data-table-highlight:  Demo content is broken, but no error messages.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#125]
Demo functionality for px-data-table-column page is broken for both tabs, editable and dropdown, compared to the data-table-column page in the archive site. 

Same issue with px-data-table-highlight.

This is the case for all the browsers.

### Data-table-column:
![screen shot 2017-07-31 at 7 05 07 pm](https://user-images.githubusercontent.com/10835611/28806235-afb4fc94-7623-11e7-8553-f9e06a7fe33b.png)

### Data-table_highlight:
![screen shot 2017-07-31 at 7 19 54 pm](https://user-images.githubusercontent.com/10835611/28806496-4db1ebc2-7625-11e7-8491-1ef8b62c10b0.png)

**Comment by randyaskin** [comment]
Someone changed the help text so it doesn't wrap anymore. Moved from the properties box into the demo box and fixed several other bugs also appearing on these two pages.
