### ISSUE TITLE
Data-table: Going into edit mode in dark theme causes the text to fade into the background.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#126]
In Data-table, when you go into edit mode, in light theme, the text remains the grey and the box is highlighted in blue and the cursor is placed at the end of the existing text indicating edit is in progress.  However, in dark theme, the text fades out to a medium grey that is barely visible on the dark background.

## Screenshots:

![screen shot 2017-07-31 at 7 26 29 pm](https://user-images.githubusercontent.com/10835611/28806788-bf9e94fa-7626-11e7-9090-5db4ae1ad497.png)

![screen shot 2017-07-31 at 7 30 03 pm](https://user-images.githubusercontent.com/10835611/28806792-c3dabf12-7626-11e7-843a-b9677c201317.png)

**Comment by randyaskin** [comment]
CSS variable added in the sass, documentation, and px-theme/px-dark-theme.
