### ISSUE TITLE
Data-table: Selecting to add table columns/rows causes an odd column addition.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#127]
In the current demo, adding table columns and table cells to the data-table results in the right hand top row to have an additional border. Unclear if the properties are supposed to add a border for each row and column not just the right hand/top row cell?

This is in all the browsers.

## Screenshot:
![2017-07-31_1939](https://user-images.githubusercontent.com/10835611/28807100-8f816a20-7628-11e7-951e-924fe82250c3.png)

**Comment by randyaskin** [comment]
One should only use `table-columns` or `table-cells`, never both. I thought about changing the demo to use a dropdown instead, but then it makes the code snippet misleading and doesn't work in CodePen, so I've just removed those toggles from the demo in v4.0.2.
