### ISSUE TITLE
Pie chart: register values hardly visible in dark theme.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#129]
Register values are hardly visible in the dark background.  Might want to revisit with design.

## Screenshot:
![screen shot 2017-08-01 at 9 25 41 am](https://user-images.githubusercontent.com/10835611/28835887-c8e0b6ae-769b-11e7-9773-f3e76a04d648.png)

**Comment by nonmetalhail** [comment]
fixed
