### ISSUE TITLE
Pie Chart: Hide register toggle doesn't seem to work.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#131]
Toggling "Hide register" to on doesn't seem to to hide the register.

## Screenshot:
![screen shot 2017-08-01 at 9 37 49 am](https://user-images.githubusercontent.com/10835611/28836293-2cc40364-769d-11e7-812b-e215e2e371f7.png)

**Comment by benoitjchevalier** [comment]
fixed
