### ISSUE TITLE
Pie Chart: Show title has an alignment issue in IE11 and FF.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#132]
Setting the show title property, works in chrome and Safari9, but in FF and IE11, the alignment is off, the value overlaying the total label.

## Screenshot
![screen shot 2017-08-01 at 9 41 15 am](https://user-images.githubusercontent.com/10835611/28836457-d584cd62-769d-11e7-86f6-4209d18e63c4.png)

**Comment by nonmetalhail** [comment]
known issue; already logged in component
