### ISSUE TITLE
Datetime Field:  404 on px-moment-imports in both dark and light theme.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#133]
#Getting a 404 on page load in dark theme.

## Screenshots:
![screen shot 2017-08-01 at 10 05 39 am](https://user-images.githubusercontent.com/10835611/28837313-30296fc2-76a1-11e7-909e-84d2ef30a5b4.png)

![screen shot 2017-08-01 at 10 11 18 am](https://user-images.githubusercontent.com/10835611/28837509-ce5e0414-76a1-11e7-87a6-b141483101b7.png)

**Comment by benoitjchevalier** [comment]
fixed in 1.0.1
