### ISSUE TITLE
Map:  Safari9 and IE11 demo doesn't work.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#135]
Do we need the transpiled version added?

## Screenshot:

![screen shot 2017-08-01 at 10 48 42 am](https://user-images.githubusercontent.com/10835611/28838992-07b27aa6-76a7-11e7-917f-52363b64fc29.png)

**Comment by ppeyro** [comment]
Safari 9 are IE11 are both back in business as of today.

**Comment by davidrleonard** [comment]
Fixed
