### ISSUE TITLE
Range Picker: Search icon is chopped off by a few pixels and is not centered.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#136]
In Rangepicker/properties, timezone search icon looks chopped by a few pixels on the left side and it's placed too high, not centered.

## Screenshot:
![screen shot 2017-08-01 at 10 53 02 am](https://user-images.githubusercontent.com/10835611/28839253-e171375a-76a7-11e7-9450-3b65f02ad4a1.png)

**Comment by katemenkhaus** [comment]
fixed with a rebuild
