### ISSUE TITLE
px-alert-message: icon placement & font size incorrect

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#137]
Alert icon should be vertically centered with two lines of text or under.

Font size is specified to be 12px, it's 15px in the build.

![image](https://user-images.githubusercontent.com/25310251/28839407-67c29290-76a8-11e7-8d31-ed80f80369f3.png)

![image](https://user-images.githubusercontent.com/25310251/28839413-6cd1f06e-76a8-11e7-84fa-f77621b5af46.png)
 
![image](https://user-images.githubusercontent.com/25310251/28839440-8ccc0256-76a8-11e7-8225-cb2b1bac1f8f.png)

Firefox 54.0.1
![image](https://user-images.githubusercontent.com/25310251/28839208-bcf7f5a8-76a7-11e7-9af1-eabedf4fda69.png)

Safari 10.1.2
![image](https://user-images.githubusercontent.com/25310251/28839168-a2419ea8-76a7-11e7-8289-ec4e1e6fabd8.png)

Chrome 60

![image](https://user-images.githubusercontent.com/25310251/28839326-2186f05a-76a8-11e7-93c8-7b10d11d54f9.png)

**Comment by katemenkhaus** [comment]
fixed in v1.03 & v1.04
