### ISSUE TITLE
dropdown: icon is missing.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#138]
If the button style is set to icon, no icon renders; however, on hover you'll get the pointer as if something is there and if you select, you'll actually get the dropdown to open.  
Should mention this is under multiple select tab.

Missing icon?

## Screenshots:
![screen shot 2017-08-01 at 11 26 58 am](https://user-images.githubusercontent.com/10835611/28840722-b86d9b14-76ac-11e7-8059-8aff6e5e5cf8.png)

![screen shot 2017-08-01 at 11 34 05 am](https://user-images.githubusercontent.com/10835611/28840955-8052346e-76ad-11e7-90d1-357e6d02214e.png)

**Comment by benoitjchevalier** [comment]
you need to fill whatever icon you want to use in the `icon` property below
