### ISSUE TITLE
PX-view-header missing icons and spacing wrong in both themes

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#139]
In both dark and light themes:
View finder missing back and next icons next to the words.
Need 5 pixels of spacing between carrot and words with deck selector. (spacing OK in Safari 10.3)
Currently:
<img width="967" alt="screen shot 2017-08-01 at 11 36 15 am" src="https://user-images.githubusercontent.com/30634949/28841238-6cd8e5e4-76ae-11e7-80e1-5015d867714f.png">
![image](https://user-images.githubusercontent.com/30634949/28841250-76edb71c-76ae-11e7-9b16-baf829b41d43.png)
<img width="82" alt="screen shot 2017-08-01 at 11 41 57 am" src="https://user-images.githubusercontent.com/30634949/28841253-794478b6-76ae-11e7-9c06-726cdb24eb06.png">
Needs to be:
![image](https://user-images.githubusercontent.com/30634949/28841286-93da0a74-76ae-11e7-8e83-7529002b4d37.png)
![image](https://user-images.githubusercontent.com/30634949/28841305-a30796d8-76ae-11e7-8280-d6ebb29c8dca.png)
Currently:
![image](https://user-images.githubusercontent.com/30634949/28841442-1ff5dbe6-76af-11e7-8c87-092749d20d7d.png)
Needs to be:
![image](https://user-images.githubusercontent.com/30634949/28841454-2bcd6bdc-76af-11e7-8016-b06c31f8b92a.png)

**Comment by randyaskin** [comment]
The deck selector was fixed this morning when I ran a rebuild to pick up the latest deck-selector.

**Comment by randyaskin** [comment]
The dark theme actionable was caught by Wade in breadcrumb earlier and updated in px-dark-theme. Change will get picked up when I trigger the rebuild when I add the icons to the demo.
