### ISSUE TITLE
file_upload: Properties alignment off

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#140]
Alignment of the last 2 properties is off under all tabs, causing the placeholder text to be chopped.

## Screenshot:
![screen shot 2017-08-01 at 11 43 13 am](https://user-images.githubusercontent.com/10835611/28841660-c921d71a-76af-11e7-8a19-02f8574cda67.png)

**Comment by katemenkhaus** [comment]
being tracked in issue 221
https://github.com/predix-ui/predix-ui.github.io/issues/221
