### ISSUE TITLE
file-upload: Codepen is broken.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#141]
Other than html nothing loads.

## Screenshot:
![screen shot 2017-08-01 at 11 54 49 am](https://user-images.githubusercontent.com/10835611/28841842-5d75fac2-76b0-11e7-90b5-089f304ddf18.png)

**Comment by randyaskin** [comment]
Unable to reproduce - works in Chrome, Safari, and Firefox for me (Mac OSX).

**Comment by mdwragg** [comment]
Works for me too.
