### ISSUE TITLE
file_upload: Error when uploading multiple files in safari9.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#142]
Selecting "multiple files" toggle and then trying to upload 2 files results in an extra row(file) with NaN msg to appear in the upload summary table.

# Screenshot:
![screen shot 2017-08-01 at 12 03 44 pm](https://user-images.githubusercontent.com/10835611/28842266-d3d75a16-76b1-11e7-9204-fc70c6b40541.png)

**Comment by talimarcus** [comment]
Fixed in https://github.com/PredixDev/px-file-upload/commit/7aca5e4df22331f9c3f2de0adf75d26c05a8863e
