### ISSUE TITLE
px-app-header demo doesn't load in Safari

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#143]
Stays at the spinner in Safari 10.1.2

Works in IE, Firefox and Chrome.

**Comment by davidrleonard** [comment]
Per @mdwragg we're holding off on transpiling app-header and app-route demos for now while we rearchitect other pieces of the site. Moving to p2 and leaving open to track our progress.

**Comment by mdwragg** [comment]
All fixed now, site fully transpiled.
