### ISSUE TITLE
file-upload: Multiple select not working in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#144]
Tried multi-select, uploading 2 files in IE11.  Nothing gets listed in the upload summary table.

## Screenshot:

![2017-08-01_1216](https://user-images.githubusercontent.com/10835611/28842688-7abc4df4-76b3-11e7-8f32-a17dab3136d5.png)

**Comment by randyaskin** [comment]
Captured by an end user here - https://github.com/PredixDev/px-file-upload/issues/15
