### ISSUE TITLE
icon: 404 on a mistyped filename.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#147]
Possible typo causing 404.
Should be design, instead of deisgn.

Same issue in index-dark-theme.html

## Screenshot:
![screen shot 2017-08-01 at 12 23 15 pm](https://user-images.githubusercontent.com/10835611/28842984-806d5c92-76b4-11e7-9eac-005f2787d0d6.png)

**Comment by benoitjchevalier** [comment]
Already fixed by Randy, I'll release it
