### ISSUE TITLE
Demo clipboard doesn't copy in Safari9.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#149]
Selecting to copy the code snippet by selecting px-clipboard at the bottom of the demo, doesn't copy the code snippet in Safari9.
Seems to work in the other browsers.

## Screenshot:
![screen shot 2017-08-01 at 12 44 01 pm](https://user-images.githubusercontent.com/10835611/28843750-2d435442-76b7-11e7-8b2e-fa6c121aa2b5.png)

**Comment by randyaskin** [comment]
Clipboard.js relies on execCommand, which is not supported in Safari 9 - see https://clipboardjs.com/

**Comment by davidrleonard** [comment]
Perhaps we should do feature detection when we load and not show the copy icon if the browser doesn't support execCommand?
