### ISSUE TITLE
inbox: codepen warnings/partially working.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#151]
Inbox codepen is mostly working.  the table doesn't render properly and getting a 403 error plus a ton of warnings about misalignment and missing fonts.

## Screenshot:
![screen shot 2017-08-01 at 12 51 05 pm](https://user-images.githubusercontent.com/10835611/28844094-5cbbfb9c-76b8-11e7-88ef-92b21a2a7a15.png)

**Comment by randyaskin** [comment]
The detail page is faked in our demo page. As it says in the CodePen, they need to use data binding and lightDom children to actually define a detailed view. The 403 looks to be related to an adblocker of some kind, not the component... I think Martin was looking at the font issues separately.
