### ISSUE TITLE
inbox: icon missing from the heading.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#153]
Old demo had the icon as part of the heading.  Refresh demo doesn't.
Unclear if this is a design change or a forgotten icon?

## Screenshot:
<img width="943" alt="screen shot 2017-08-01 at 12 57 38 pm" src="https://user-images.githubusercontent.com/10835611/28844428-6d84393e-76b9-11e7-8604-902d5462804b.png">

**Comment by randyaskin** [comment]
I was following Wade's updated spec - https://ge.ent.box.com/notes/179741744614
