### ISSUE TITLE
px-app-nav: Submenu appears at top of screen or doesn't display

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#156]
**Chrome 60 & Firefox 54.0.1**

- Horizontal nav configuration > Click on Assets
- Menu appears under grey bar at top of screen.

**Safari 10**
Menu doesn't display until you resize the menu
- Horizontal nav configuration > click on assets
- Menu doesn't appear
- Resize screen
- Menu appears

**Works as designed in IE11**

![image](https://user-images.githubusercontent.com/25310251/28844967-5572e4e2-76bb-11e7-8a79-a5b6817b2e78.png)

![image](https://user-images.githubusercontent.com/25310251/28845268-495fc4da-76bc-11e7-9cbc-354485695dfa.png)

![image](https://user-images.githubusercontent.com/25310251/28845276-4fd77ede-76bc-11e7-8c36-6a082f3011f2.png)

Works on IE 11

**Comment by randyaskin** [comment]
Also captured here - https://github.com/PredixDev/px-app-nav/issues/71
