### ISSUE TITLE
px-app-nav: Text doesn't display in Firefox

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#157]
All fonts are missing from app-nav demo page in Firefox 54.0.1. Doesn't appear to affect any other repos.

Works correctly in Safari, Chrome and IE11. 

![image](https://user-images.githubusercontent.com/25310251/28845586-68aa6f4c-76bd-11e7-9939-6d10a903fc9a.png)

**Comment by benoitjchevalier** [comment]
fixed in px-theme 3.0.7
