### ISSUE TITLE
key-value-pair:  padding between the valuepair is off in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#159]
Padding for the "Alpha" size is off in IE11 vs. other browsers.
Other size values seem to be more reasonable.

## Screenshot:
![2017-08-01_1339](https://user-images.githubusercontent.com/10835611/28846184-561cdc32-76bf-11e7-82c6-14560cbe6a5d.png)

**Comment by talimarcus** [comment]
Fixed in https://github.com/PredixDev/px-key-value-pair/commit/45e9a2409e6f58aa41545dab3c60b8da32707108
