### ISSUE TITLE
px-app-nav: Incorrect overflow icon

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#160]
- Resize window to ~400px in Safari
- Overflow Icon displayed is px-nav:collapse
- Overflow icon should be px-utl:overflow

![image](https://user-images.githubusercontent.com/25310251/28846214-71157b70-76bf-11e7-8729-a124a74a49d3.png)

**Comment by benoitjchevalier** [comment]
fixed in 2.0.3
