### ISSUE TITLE
px-tabs disable option not available

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#161]
Disabled option not available for dark & light themes
![image](https://user-images.githubusercontent.com/30634949/28846423-3bff4208-76c0-11e7-8787-7d028530db78.png)
![image](https://user-images.githubusercontent.com/30634949/28846432-45ad1e24-76c0-11e7-8e49-f585489ba91f.png)

**Comment by randyaskin** [comment]
Subsequent iterations of the spec included notes that said that Hans didn't see a use case for disabled tabs in industrial applications, so it was never developed.
