### ISSUE TITLE
KPI:  Codepen gets 2 404's and an error on console.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#162]
KPI codepen seems to work, but there are 2 msgs on the console when codepen is opened and also 404's on a few files.

# Screenshot:
![screen shot 2017-08-01 at 1 50 15 pm](https://user-images.githubusercontent.com/10835611/28846522-9e9c05e0-76c0-11e7-812c-5b452bb9fdff.png)

**Comment by randyaskin** [comment]
Will likely need to be updated/replaced along with all the other broken px-vis CodePens. Related: #105

**Comment by randyaskin** [comment]
Elliot replacing all viz Codepens with Glitches.
