### ISSUE TITLE
px-app-nav: Incorrect Home icon being used

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#163]
AppNav demo is using 22x22 version of the home icon which is causing the stroke to be thicker than the rest of the icons. Should be using px-fea:home which is 32x32.

![image](https://user-images.githubusercontent.com/25310251/28846487-7d895e02-76c0-11e7-8c4f-2e93fa524f6c.png)

**Correct icon:**
![image](https://user-images.githubusercontent.com/25310251/28846541-af15778a-76c0-11e7-8d42-7b2b64649f6f.png)

**Comment by davidrleonard** [comment]
The nav items should default to px-fea icons, NOT px-nav icons (except where a px-nav icon exists and does not have a px-fea equivalent), per @skistz.

This needs to be updated across px-app-nav with documentation added to px-app-nav (e.g. update all demos and examples/*.html to use px-fea icons, update tests to px-fea icons) to explain this.

**Comment by talimarcus** [comment]
Fixed in https://github.com/PredixDev/px-app-nav/pull/74
