### ISSUE TITLE
px-table-view rows size doesn't work in Chrome

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#164]
Can't choose a row size in dark and light themes in Chrome
![image](https://user-images.githubusercontent.com/30634949/28846746-71d58918-76c1-11e7-916d-b8e32414fe8f.png)
![image](https://user-images.githubusercontent.com/30634949/28846758-77691228-76c1-11e7-9238-e73e4ef1c4f7.png)

**Comment by randyaskin** [comment]
Looks like a caching problem, the top screenshot shows the old dropdown but the new toggle, meaning the wires got crossed somewhere. I just see the bottom version on mine.
