### ISSUE TITLE
px-login:  Popover right location way off to the right.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#166]
Choosing popover location to right and then selecting the sign on icon will open the popover too far to the right.
Happens on all browsers checked, chrome, ie11, ff, and safari9.

# Screenshot:
![screen shot 2017-08-01 at 1 58 37 pm](https://user-images.githubusercontent.com/10835611/28846845-cb9b91e0-76c1-11e7-99a5-346b5b096804.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.4.
