### ISSUE TITLE
px-forms-design has a clear button on IE

### ISSUE THREAD

**Issue by waifong** [predix-ui/predix-ui.github.io#167]
Remove clear "X" for Input Field on IE

**Comment by davidrleonard** [comment]
@waifong Can you include a screenshot that shows what you mean? Thanks.

**Comment by waifong** [comment]
![forms-design-ie](https://user-images.githubusercontent.com/30637855/28849868-0ae7135e-76ce-11e7-8aae-e3f33ff1ea3f.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.2.
