### ISSUE TITLE
px-calendar-picker blocked out past + future dates

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#168]
Block future and block past dates turned on and display mode is day) Within the blocked out sections of the calendar and you move through the months in quick succession, greyed out dates start of black and gradually turn to grey.

Sorry for the run-on sentence/if this doesn't make sense...you have to see it to believe it haha.

**Comment by davidrleonard** [comment]
@Lizrichardson53 can you include the following info:

1. A screenshot showing what is not working? Arrows to the broken section help
2. The browser you were testing in including its version (tap the browser's name in the menu bar and click about to get the version). Thanks!

**Comment by davidrleonard** [comment]
cc @Menkhaus-ge

**Comment by Lizrichardson53** [comment]
This occurs in both dark & light themes.
A. Here is a screen grab of what I'm talking about. Look at the first and last couple days of the month. In the light theme, dates fade from black to grey. In the dark theme, dates fade from white to grey.
[Calendar-picker Bug .zip](https://github.com/predix-ui/predix-ui.github.io/files/1192018/Calendar-picker.Bug.zip)

B. Chrome, Safari 10, Firefox

**Comment by JusticeRises** [comment]
It also occurs when you have both "Block Future Dates" and "Block Past Dates" selected while jumping from Display Mode - "Date" to Display Mode "Month" or "Year". It does not occur when you start from month or year.

**Comment by randyaskin** [comment]
I fixed this in the latest version by removing the btn--bare transition from the calendar cells so that they change colors (and borders/backgrounds) immediately instead of animating in/out.
