### ISSUE TITLE
px-branding-bar: Predix logo is off baseline

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#169]
Predix logo on the right side of the branding bar is off the baseline by a couple pixels. Consistently off in Chrome, Safari and IE. Everything appears to be shifted up a few pixels in Firefox.

**Chrome 60:**
![image](https://user-images.githubusercontent.com/25310251/28846958-498e38fa-76c2-11e7-9f76-e41e2fb3ba2d.png)
![image](https://user-images.githubusercontent.com/25310251/28847588-a96e3e6c-76c4-11e7-94ee-d3ae853fbad8.png)

**Safari 10**
![image](https://user-images.githubusercontent.com/25310251/28847146-0e555e66-76c3-11e7-9ad0-d8df33df9ae6.png)

**Firefox**
![image](https://user-images.githubusercontent.com/25310251/28847128-fefe70ba-76c2-11e7-9b04-a12039b11c5d.png)

**Comment by mdwragg** [comment]
Just made a change by request of St Wade. Can you recheck this @skistz? (may take a while to come down the pipe from build etc.
