### ISSUE TITLE
px-map: flex to size toggle removes the map all together.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#170]
In Properties, flex to size toggle is disabled, but not the case for the rest of the browsers.
Tried toggling it on FF, and the map tiles were all removed with no error in console.

## Screenshots:
![screen shot 2017-08-01 at 2 18 07 pm](https://user-images.githubusercontent.com/10835611/28847634-d3410602-76c4-11e7-8b05-bb60a01b0b12.png)

![screen shot 2017-08-01 at 2 21 13 pm](https://user-images.githubusercontent.com/10835611/28847661-f48e360e-76c4-11e7-9ae8-c78d546219c6.png)

**Comment by benoitjchevalier** [comment]
I'm actually going to leave that to @davidrleonard , but it looks ok to me apart from the fact that the "flex to size" is disabled for me on FF (maybe on purpose?)

the fact that the map disappear when turning it on seem like the expected result since the chart itself hasn't been given a size from what I can see

**Comment by talimarcus** [comment]
The `flexToSize` property is supposed to be on and disabled. We put it in the Properties panel just to show that it's a property that can be set, but it should always be on in the demos. 

I have checked Chrome, Firefox, and Safari 9 & 10, and the property is on and *disabled* in all those browsers (for me). But Liz was also seeing it enabled in Chrome: https://github.com/predix-ui/predix-ui.github.io/issues/213.

@ppeyro did you only see it enabled in Firefox?

**Comment by talimarcus** [comment]
Cannot replicate `flexToSize` being enabled in any browser. Closing.
