### ISSUE TITLE
px-calendar-picker shrink on, doesn't do anything in live preview

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#171]
When select shrink for calendar picker, nothing happens in the live preview
![image](https://user-images.githubusercontent.com/30634949/28847877-af3bacca-76c5-11e7-95b7-428df2e929a1.png)

**Comment by benoitjchevalier** [comment]
it's not obvious since we don't have border but it does have an impact:

* (optional)
* If set, allows the calendar picker to shrink rather than have a constant size.
* Typically the height would shrink when choosing months or years

works as intended in this demo
