### ISSUE TITLE
MEGABUG: Fix transpilation errors

### ISSUE THREAD

**Issue by davidrleonard** [predix-ui/predix-ui.github.io#173]
A lot of our bugs are caused because components need to be transpiled. The following will likely be fixed by transpilation:

* [x] #63 (px-tree)
* [x] #92 (breadcrumbs)
* [x] #97 (context-browser)
* [x] #135 (map)
* [x] #87 (app-header & breadcrumbs)
  * [x] breadcrumbs
  * [ ] app-header
* [ ] #143 (app-header)

Component demos rebuilt:

* [x] px-app-nav
* [x] px-map
* [x] px-breadcrumbs
* [x] px-tree
* [x] px-context-browser
* [ ] px-app-header
* [ ] px-app-route

**Comment by davidrleonard** [comment]
@ppeyro px-context-browser is transpiled/fixed.

**Comment by davidrleonard** [comment]
Holding off on app-header/app-route for now (see #143). All the rest are fixed.

**Comment by ppeyro** [comment]
Resurrecting this since David really misses dealing with transpilation issues.
Context browser is back to being broken on the site.

**Comment by mdwragg** [comment]
Can we close this now @davidrleonard @ppeyro ???

**Comment by mdwragg** [comment]
All fixed - just fixed app header, finally....
