### ISSUE TITLE
Predix-ui.com homepage: Mobile site flashes when loading/toggling light to dark

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#175]
Firefox, IE 11 & Safari: 
- visit www.predix-ui.com
- brief flash of mobile homepage image and style-less homepage before full page loads
- also occurs when you toggle from light to dark

![image](https://user-images.githubusercontent.com/25310251/28848549-3a154142-76c8-11e7-9996-f72aaf2c4ea6.png)

![image](https://user-images.githubusercontent.com/25310251/28848663-a84487d6-76c8-11e7-8869-c6132aa76219.png)

**Comment by mdwragg** [comment]
@Menkhaus-ge is on it
