### ISSUE TITLE
px-slider top number labels are cut off in live preview

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#176]
In Firefox & Chrome:
When is range and show labels are turned on and min label position is set to top, top number labels are cut off in the live preview.

![image](https://user-images.githubusercontent.com/30634949/28848747-f8198bee-76c8-11e7-92a5-68055c3883d0.png)
![image](https://user-images.githubusercontent.com/30634949/28848752-0147988c-76c9-11e7-8348-a283e7b0e3e1.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.2.
