### ISSUE TITLE
px-map: dropdown is overlaid by the tiles.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#178]
When you open the view children dropdown, the tiles overlay on top of the last 3 items in the dropdown.

This is happening in Chrome and FF. (Safari9 and IE11 still waiting on the the transpiled bug fix so they can render the map)

## Screenshot:
![screen shot 2017-08-01 at 2 53 48 pm](https://user-images.githubusercontent.com/10835611/28848891-742f8300-76c9-11e7-9b28-8f0ce4b0fc75.png)

**Comment by ppeyro** [comment]
One additional note:  If you select px-map-popup-data where the properties is wider the issue is resolved. Possibly a z index issue?

**Comment by talimarcus** [comment]
I am looking into this

**Comment by davidrleonard** [comment]
Fixed in predixdev/px-map@v2.1.0
