### ISSUE TITLE
px-slider min/max label numbers cut off by slider 

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#181]
In Firefox, Safari, Chrome
When min/max label positions are set to top & bottom, the slider can sit in front of numbers, blocking what the min/max numbers are. 
Add more space between the number and slider.

![image](https://user-images.githubusercontent.com/30634949/28848942-a241ed96-76c9-11e7-950e-82baaef9d814.png)
![image](https://user-images.githubusercontent.com/30634949/28849064-2e7a7e5e-76ca-11e7-87f4-1516d749f1a1.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.2.
