### ISSUE TITLE
px-progress-bar infinite animation glitch in Safari

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#183]
Safari 10
Dark & light theme:
Once the progress bar animation reaches the end, the progress bar glitches and jumps backward before moving forward.
[Progress Bar Glitch.zip](https://github.com/predix-ui/predix-ui.github.io/files/1192103/Progress.Bar.Glitch.zip)

**Comment by talimarcus** [comment]
Same on Safari 9, but even worse (shakier)

**Comment by randyaskin** [comment]
Already captured here: https://github.com/PredixDev/px-progress-bar/issues/3
