### ISSUE TITLE
Slider: Safari/Chrome -  max label doesn't show up when labels are enabled

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#186]
![bc8ytdg2bhgaccaigigaigkiccaigigaigkiccaigigaigkiccaigigaigkiccaigigaigkicbd6cwvnqfzwlnlzaaaaaelftksuqmcc](https://user-images.githubusercontent.com/25111262/28849723-443d3008-76cd-11e7-9540-fa2cac2f47f9.png)

**Comment by vonsichart200** [comment]
Chrome: Saw the same behavior in Chrome in the Light & Dark theme, too.

**Comment by randyaskin** [comment]
Fixed in v2.0.2.
