### ISSUE TITLE
px-popover set to left orientation is cut off/sits under left nav in live preview

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#188]
Chrome, IE 11, Safari, & Firefox
When the popover orientation is set to left, the live preview is cutoff by the left tree nav rather than sitting on top of the menu.
![image](https://user-images.githubusercontent.com/30634949/28849740-5c539fe2-76cd-11e7-8616-c2da412c9791.png)
![image](https://user-images.githubusercontent.com/30634949/28849782-993e77c4-76cd-11e7-86de-4af8c541b920.png)

**Comment by benoitjchevalier** [comment]
Loggeds as an enhancement request: https://github.com/PredixDev/px-popover/issues/new
