### ISSUE TITLE
Firefox: Font position 2 pixels too high across multiple components

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#189]
Font position too high in "Buttons":
![box-image-3](https://user-images.githubusercontent.com/25111262/28849863-055ace62-76ce-11e7-96e0-6d39ed066409.png)

Font sits too high in "Tool Tip":
![box-image-2](https://user-images.githubusercontent.com/25111262/28849850-f70f6f66-76cd-11e7-8d80-5e8c1fd4e778.png)

**Comment by randyaskin** [comment]
Fixed in tooltip. I don't know if we'll ever fix in FF, I tried a bunch of different ways without success.
