### ISSUE TITLE
Datetime Field & Datetime Picker & Datetime Range Field: Timezone search mechanism not always returning all values

### ISSUE THREAD

**Issue by JusticeRises** [predix-ui/predix-ui.github.io#190]
In both light and dark themes for Chrome, Firefox, and Safari 10, the search mechanism for timezones only seems to work when I search for strictly numbers.

For example, I search for "Etc/GMT+1" which should return back results for Etc/GMT+1, Etc/GMT+10, Etc/GMT+11 and so on. However, all results get filtered out the second I add the number after the addition sign. 

The more I look at it, the more it seems that the addition sign is the culprit for this issue because all other searches without it seem to be working which is awesome.

<img width="394" alt="screen shot 2017-08-01 at 3 29 08 pm" src="https://user-images.githubusercontent.com/5334481/28850334-d6ec8658-76d0-11e7-8fb5-d703a0ee75bd.png">

<img width="390" alt="screen shot 2017-08-01 at 3 29 31 pm" src="https://user-images.githubusercontent.com/5334481/28850336-d8e725f8-76d0-11e7-97c2-4cc606998a85.png">

**Comment by benoitjchevalier** [comment]
moving to typeahead https://github.com/PredixDev/px-typeahead/issues/17
