### ISSUE TITLE
Datetime Field - Firefox: Light theme content on page is not visible

### ISSUE THREAD

**Issue by JusticeRises** [predix-ui/predix-ui.github.io#191]
When visiting the datetime field component using Firefox, all of the header text and parts of the component are not visible. The content is clearly there, but just not the right color. It looks perfectly fine using the dark theme and for both themes in Chrome and Safari.

<img width="1368" alt="screen shot 2017-08-01 at 3 49 28 pm" src="https://user-images.githubusercontent.com/5334481/28850441-6a6cee9a-76d1-11e7-9975-8c6238eff89c.png">

<img width="1369" alt="screen shot 2017-08-01 at 3 50 41 pm" src="https://user-images.githubusercontent.com/5334481/28850442-6bfbcc22-76d1-11e7-8d8e-b756b7a531ad.png">

**Comment by benoitjchevalier** [comment]
Fixed in px-theme 3.0.7
