### ISSUE TITLE
Viewheader:  Demo doesn't load with a Script error in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#192]
No luck viewing view header in IE11.

## Screenshot:
![2017-08-01_1605](https://user-images.githubusercontent.com/10835611/28850791-8cbed614-76d3-11e7-9ca8-9242eed51c54.png)

**Comment by talimarcus** [comment]
This was because the code hadn't been transpiled, but it is now and working 👍
