### ISSUE TITLE
Datetime Picker & Datetime Range Field: Old time zone property icon is still present

### ISSUE THREAD

**Issue by JusticeRises** [predix-ui/predix-ui.github.io#193]
What I believe to be the old search icon is still present in the Time Zone category on the Datetime Picker component. This is present in Safari 10, Chrome, and Firefox for both the light and dark themes.

Because it is an old icon, it gets slightly clipped on the edges.

<img width="189" alt="screen shot 2017-08-01 at 4 10 50 pm" src="https://user-images.githubusercontent.com/5334481/28851009-b08b7f42-76d4-11e7-8a26-a7ef795007e3.png">

<img width="212" alt="screen shot 2017-08-01 at 4 10 59 pm" src="https://user-images.githubusercontent.com/5334481/28851010-b224ee1a-76d4-11e7-9db7-2f128ff28db1.png">

**Comment by randyaskin** [comment]
I rekicked the builds in Travis to pick up the latest px-typeahead.
