### ISSUE TITLE
px-map tile layer doesn't load in Firefox

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#194]
The symbol markers shows up but the tile layer doesn't show up in any px-map components.
![image](https://user-images.githubusercontent.com/30634949/28851478-9ca3be06-76d7-11e7-90cf-26884fdc778e.png)
![image](https://user-images.githubusercontent.com/30634949/28851486-a7e9382c-76d7-11e7-95a3-b5fa3e5ba4f6.png)
![image](https://user-images.githubusercontent.com/30634949/28851492-b0aa3cd6-76d7-11e7-8da0-6c54529b1958.png)

**Comment by mdwragg** [comment]
This is working for me, @Lizrichardson53, can you retest? Could be network related...

**Comment by Lizrichardson53** [comment]
Hmm.. it's still occurring for me.

**Comment by Lizrichardson53** [comment]
Sorry accidentally took a screenshot. Here it is
![image](https://user-images.githubusercontent.com/30634949/28852740-59737ef6-76e0-11e7-81e9-fa28daf24ac8.png)

**Comment by Lizrichardson53** [comment]
It's loading for Justice, maybe its just my connection?

**Comment by davidrleonard** [comment]
@Lizrichardson53 if you can reproduce this let me know and I'll come take a look. Leave the browser window up.

**Comment by Lizrichardson53** [comment]
@davidrleonard I've got it up and will leave it up. When you get a chance you can check it out.

**Comment by ppeyro** [comment]
@Lizrichardson53 Did you clear your cache?  If not that could cause it to be glitchy.

**Comment by mdwragg** [comment]
Closing at @talimarcus 's request.
