### ISSUE TITLE
px-login sign in words sign in are not centered with icon

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#195]
Safari 10
Words sign in are not centered with the icon.
![image](https://user-images.githubusercontent.com/30634949/28851606-a8d329d6-76d8-11e7-86ae-c15ecf071614.png)
![image](https://user-images.githubusercontent.com/30634949/28851610-b12591f0-76d8-11e7-81dd-e3a56b6e48cc.png)
![image](https://user-images.githubusercontent.com/30634949/28851615-b8bb48e2-76d8-11e7-9b87-d5af0bc250cf.png)

**Comment by randyaskin** [comment]
Fixed.
