### ISSUE TITLE
Context Browser: Filter icon is missing in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#196]
## Screenshot:
![2017-08-01_1638 copy](https://user-images.githubusercontent.com/10835611/28851552-2eb2a74e-76d8-11e7-92f9-f822a5c25742.png)

**Comment by talimarcus** [comment]
Looking into this

**Comment by talimarcus** [comment]
Fixed in https://github.com/PredixDev/px-context-browser/commit/d1170e05b527213e6bb2268155b4104f19b6b200
