### ISSUE TITLE
px-KPI Status label pushed to the right, not left justified in Chrome & Safari

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#198]
Chrome & Safari
Dark & Light Themes:
Status label (12%) is pushed to the right to far and not left aligned with unit of measure (USD).
12% and USD should both be left aligned. 
Also occurs with bar & win/loss.
![image](https://user-images.githubusercontent.com/30634949/28852029-254893b4-76db-11e7-8ef5-e23712079817.png)

![image](https://user-images.githubusercontent.com/30634949/28852020-19876988-76db-11e7-9435-f84188fcc05c.png)
Guidlines:
![image](https://user-images.githubusercontent.com/30634949/28852065-59cb5388-76db-11e7-8b29-3acf8e5e7307.png)

**Comment by randyaskin** [comment]
That's just the white space built into the px-icon to make sure that the arrow appears in the middle of it's 30x30 (or whatever) box. The opposite problem would occur if I moved it to the left and we used a different icon that better fills the square container.
