### ISSUE TITLE
typeahead:  Properties width too narrow, placeholder text is chopped.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#199]
## Screenshot:

![screen shot 2017-08-01 at 5 09 06 pm](https://user-images.githubusercontent.com/10835611/28852215-63ccbd12-76dc-11e7-8590-fc091a1abe9f.png)

**Comment by randyaskin** [comment]
It's a standard width that all of our demo properties containers use, just because this text string happens to be too long is not really an error. Many of our components contain demo inputs that are longer than the space available, trimming is the intended behavior of input fields.
