### ISSUE TITLE
px-number-formatter: console error on invalid `culture` value

### ISSUE THREAD

**Issue by talimarcus** [predix-ui/predix-ui.github.io#200]
Error is thrown in console when you enter an invalid `culture`, but not when any of the other Properties values are invalid (e.g. if you put nonsense in for `format`).

Browsers: Chrome, Safari, IE

<img width="1434" alt="screen shot 2017-08-01 at 5 14 21 pm" src="https://user-images.githubusercontent.com/9092541/28852277-e0c9b6ee-76dc-11e7-8a7d-e8152c714850.png">

**Comment by benoitjchevalier** [comment]
that's "normal", it won't accept an invalid entry and the entry is checked on every character press. If passing a valid entry at once it should work (and generally this will be done programmatically)
