### ISSUE TITLE
px-inbox icon (orange diamond, block 2) missing, not to the left of drum anomaly

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#202]
Firefox, Chrome, & Safari
The icon: orange diamond with 2 inside should be to the left of drum anomaly, but isn't there.

![image](https://user-images.githubusercontent.com/30634949/28852288-e87bda48-76dc-11e7-84ef-3d69c76ace51.png)
Guidelines:
![image](https://user-images.githubusercontent.com/30634949/28852299-fbc9644e-76dc-11e7-8f88-66330afe5e55.png)

**Comment by randyaskin** [comment]
This is on purpose, to illustrate the functionality we added in the redesign - the ability to omit the icon badge completely.

**Comment by Lizrichardson53** [comment]
I didn't realize that, thank you Randy!
