### ISSUE TITLE
CSS Modules - Code: Missing words

### ISSUE THREAD

**Issue by JusticeRises** [predix-ui/predix-ui.github.io#203]
"You can change style variables..." -> "You can change the style of variables..."

https://www.predix-ui.com/#/css/px-code-design/  found under the Customize Styles section.

<img width="805" alt="screen shot 2017-08-01 at 5 14 04 pm" src="https://user-images.githubusercontent.com/5334481/28852339-3321e786-76dd-11e7-83b3-35dabaa196c0.png">

**Comment by randyaskin** [comment]
No, that's actually correct. You can change [the value of] style variables [in order] to customize the design... not changing the styles of variables, but changing the actual *style variables*

**Comment by JusticeRises** [comment]
Whoops! My mistake. I see that now.

Sorry about that.
