### ISSUE TITLE
typeahead: demo doesn't load properly in IE11

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#204]
Loading the demo on IE11 has issues with the width of properties and if you switch between the tabs it causes the browser to crash.

## Screenshot:
![2017-08-01_1718](https://user-images.githubusercontent.com/10835611/28852411-bf593830-76dd-11e7-8afc-bb048b688872.png)

**Comment by mdwragg** [comment]
Fixed by 2d593b617afc0a244d9121d259f7a31acd481c46
