### ISSUE TITLE
px-map "disable touch zoom" can still zoom

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#206]
Chrome, Safari, Firefox
When "disable touch zoom" and "disable scroll zoom" are turned on, you can still zoom.

[Map- Zoom Bug.zip](https://github.com/predix-ui/predix-ui.github.io/files/1192329/Map-.Zoom.Bug.zip)

**Comment by talimarcus** [comment]
@Lizrichardson53 `disableTouchZoom` is for touch devices, but weird that you can still zoom even with `disableScrollZoom` on. I can't replicate this on any of those browsers on my machine, can you come show me when you have a minute?

**Comment by talimarcus** [comment]
Cannot replicate on my machine or Liz's. Closing.
