### ISSUE TITLE
px-timeline: When enhanced option is enabled, crashes IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#207]
## Screenshot:

![2017-08-01_1752](https://user-images.githubusercontent.com/10835611/28853063-ae330b62-76e2-11e7-92f5-51d4c5d446bb.png)

**Comment by randyaskin** [comment]
Not able to reproduce, seems to be working (though it takes a second to redraw) in IE11 on the Surface.
