### ISSUE TITLE
px-tree & px-nav: Transpiled version is 404'ng in safari9.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#208]
Missing an animation file and toggle in both px-tree & px-nav.

## Screenshot:
![screen shot 2017-08-01 at 6 01 43 pm](https://user-images.githubusercontent.com/10835611/28853212-c3c0863e-76e3-11e7-9911-1cef9513569f.png)

**Comment by mdwragg** [comment]
Dropped support for Safari 9.x so closing this 👍
