### ISSUE TITLE
all browsers: when loading the home page there is an un-styled page that renders momentarily.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#210]
This wasn't happening earlier in the day.  Started happening about an hour or so ago.
It's hard to capture it and attach here, but it's visible quite easily in IE11 when you load the home page.

Not seeing this in any other browsers.

**Comment by mdwragg** [comment]
I don't see this on Chrome 🤔 

Safari: yes
FF: yes
Edge: no
IE: yes

**Comment by davidrleonard** [comment]
We've switched from transpiling in the iframe. I'm closing this issue in favor of other transpilation issues that are relevant.
