### ISSUE TITLE
IE11: dark theme is not loading in transpiled version for context browser, breadcrumb and tree.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#211]
## Screenshot:

![2017-08-01_1843](https://user-images.githubusercontent.com/10835611/28854103-e6ad6d8c-76e9-11e7-8e1e-16118da51d35.png)

### Breadcrumb dark theme failing to load:
![screen shot 2017-08-01 at 8 28 13 pm](https://user-images.githubusercontent.com/10835611/28856457-0a94af54-76f8-11e7-8acc-a7ddb417781d.png)

**Comment by davidrleonard** [comment]
Runtime theming added to all of the above.
