### ISSUE TITLE
Predix-ui Homepage: lncorrect logo for dark theme

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#212]
When swapping to dark theme on the home page, the logo needs to be swapped too so it retains contrast against the background. Replace the dark theme logo with img/predix_ds_logo_dark.webp

Alternate fix: find a color for "Design System" that works on both backgrounds.

**Comment by mdwragg** [comment]
Picture is worth a thousand words... Can you show us what you mean, just so we're clear. Thanks.

**Comment by davidrleonard** [comment]
@Menkhaus-ge I think this should be a quick fix building on the work we did yesterday?

**Comment by skistz** [comment]
Current:
![image](https://user-images.githubusercontent.com/25310251/28884541-1ae0bd8e-7767-11e7-92fa-e1cef44fe820.png)

With the correct image:
![image](https://user-images.githubusercontent.com/25310251/28884569-30f8308e-7767-11e7-91ea-7087d2e84b51.png)

Image location: https://www.predix-ui.com/img/predix_ds_logo_dark.webp

**Comment by mdwragg** [comment]
Cool, I understand, thanks. We need the png fallback too @skistz if you've got it.

**Comment by mdwragg** [comment]
Ignore me, I saw where you were serving that webp from now ;) We already have it...

**Comment by skistz** [comment]
👍 

They're all up there including @2x images for retina displays.

Light theme:
https://www.predix-ui.com/img/predix_ds_logo.webp
https://www.predix-ui.com/img/predix_ds_logo.png
https://www.predix-ui.com/img/predix_ds_logo@2x.png
https://www.predix-ui.com/img/predix_ds_logo@2x.webp

Dark theme:
https://www.predix-ui.com/img/predix_ds_logo_dark.webp
https://www.predix-ui.com/img/predix_ds_logo_dark.png
https://www.predix-ui.com/img/predix_ds_logo_dark@2x.png
https://www.predix-ui.com/img/predix_ds_logo_dark@2x.webp

**Comment by mdwragg** [comment]
Good call, have we got the 2x support going @Menkhaus-ge? - I meant to check but didn't get round to it...

**Comment by katemenkhaus** [comment]
I'm looking into it

**Comment by katemenkhaus** [comment]
pushed fix in commit c8b5fe 
https://github.com/predix-ui/predix-ui.github.io/commit/c8b5fe
