### ISSUE TITLE
px-map Can't turn on/off the flex to size toggle in Chrome & Firefox

### ISSUE THREAD

**Issue by Lizrichardson53** [predix-ui/predix-ui.github.io#213]
You can't turn on/off the flex to size toggle in Chrome and Firefox, but can in Safari.
![map-flex to size-01](https://user-images.githubusercontent.com/30634949/28885437-c8b2e9de-776a-11e7-80da-1f0d16add65c.png)
[Map flex to size toggle.zip](https://github.com/predix-ui/predix-ui.github.io/files/1194688/Map.flex.to.size.toggle.zip)

**Comment by talimarcus** [comment]
This is the correct behavior in Chrome/Firefox, incorrect in Safari (the user should not be able to set the `flexToSize` property). My guess though is that this is a problem with px-demo, not px-map. Will look into it.

**Comment by talimarcus** [comment]
I'm actually not seeing this in Safari. That property is disabled for me (as it should be). Are you on Safari 9 or 10 @Lizrichardson53 ?

**Comment by talimarcus** [comment]
Working for me on Safari 9 & 10 ... what is wrong with your machine Liz?! 😄

**Comment by ppeyro** [comment]
@talimarcus I saw it enabled on firefox yesterday, and if you toggled it, it would remove the map all together.  That's why I filed  #170.   But, it looks disabled on safari9 and firefox today.  Someone must have fixed it and pushed the change to the site?

**Comment by talimarcus** [comment]
@ppeyro there haven't been any updates to the demo page in the last week, and even those updates wouldn't have affected that property 🤔  I'll try to reproduce it again on Liz's machine, but otherwise I think we can just close this one. @davidrleonard can correct me if he thinks we should do more digging.

**Comment by talimarcus** [comment]
Cannot replicate `flexToSize` being enabled in any browser. Closing.
