### ISSUE TITLE
Predix-ui.com links on homepage don't update tree nav

### ISSUE THREAD

**Issue by skistz** [predix-ui/predix-ui.github.io#214]
Need to fix the routing for the links on the homepage.

Example:
- visit predix-ui.com in any browser
- click on Learn More in the hero image (or Download the Starter Kit or Start Developing)
- Tree still set on Home making the Home link not function.

![image](https://user-images.githubusercontent.com/25310251/28886009-c296c550-776c-11e7-90c6-759deac7da85.png)

**Comment by katemenkhaus** [comment]
fixed on commit 95f18a9
