### ISSUE TITLE
IE11: Animation on the homepage is no longer rendering in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#215]
The animation was there last night and has now disappeared all together in IE11 only.

No Errors in console log either.

# Screenshot:
![2017-08-02_1030](https://user-images.githubusercontent.com/10835611/28886369-1c7b91c6-776e-11e7-9b5f-cc0c853da749.png)

**Comment by ppeyro** [comment]
Lowering to p2.

**Comment by katemenkhaus** [comment]
fixed on commit 5368c4e
https://github.com/predix-ui/predix-ui.github.io/commit/5368c4e
