### ISSUE TITLE
Timeline:  Arrow color should be $grey10, it's currently $grey15

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#216]
A slight color adjustment may be needed to match the design.

## Screenshot:
![screen shot 2017-08-02 at 11 00 34 am](https://user-images.githubusercontent.com/10835611/28887489-35bae0a2-7772-11e7-951d-cc44fec7e03f.png)

### Design:

![screen shot 2017-08-02 at 11 01 06 am](https://user-images.githubusercontent.com/10835611/28887530-4fe4e2f2-7772-11e7-8054-94c70946dba6.png)

**Comment by randyaskin** [comment]
Fixed in v1.0.3.
