### ISSUE TITLE
px-table-row: Image is missing in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#217]
In px-table-row:
placehold.it image gets blocked because of security protocol. Only happening in IE11.

## Screenshot:
![2017-08-02_1435](https://user-images.githubusercontent.com/10835611/28896164-2d117678-7790-11e7-8f90-3725b50afb70.png)

**Comment by randyaskin** [comment]
I caught and fixed this the day before you did... I just didn't realize that the Travis build errored. 😞
