### ISSUE TITLE
px-table-row: icon should be removed on the left hand side when swipe left toggle is on.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#218]
This is confusing since looking at it on the desktop.
Swiping left should remove the icon completely. But it seems like there is a bit left over after the swipe is complete.  
On the actual ipad though, the icon only appears in landscape mode, it's completely clippef in portrait mode before the swipe happens.

Unclear what the functional requirements are?

## Screenshot:
![screen shot 2017-08-02 at 2 39 40 pm](https://user-images.githubusercontent.com/10835611/28896310-c131a116-7790-11e7-85a3-0d83c9736fd7.png)

**Comment by randyaskin** [comment]
To your point, Jonnie designed this in a vacuum without our designers weighing in or providing feedback, but it does match the native iOS functionality:
![maxresdefault](https://user-images.githubusercontent.com/2130613/28946725-e97617ee-7860-11e7-9703-5baee32ca3bc.jpg)

A row goes off screen most of the way, so a preview of the row contents is still visible and it's obvious that you can swipe it back onto the screen again to cancel. The actual content of the row (the gear icon, in this case) is completely arbitrary/configurable.
