### ISSUE TITLE
iOS Safari: side nav scrolling is broken

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#219]
Notice this on the iphone. 
ipad seems to behave properly.

On the iphone with the side nav open,  tried to swipe down to view a specific component but wasn't able to swipe up/down at all.
This is both in portrait and landscape mode.

Logging this for tracking even though mobile is not a priority.

**Comment by randyaskin** [comment]
Works fine on Chrome for iOS (once you expand a category so that overflow occurs, otherwise the page scrolls in the background). Scrolling seems completely broken in iOS Safari.
