### ISSUE TITLE
Spinner:  When the size property is selected, spinner turns into a tiny spinning circle in IE11...

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#220]
Only in IE11.....

#Screenshot:
![2017-08-02_1508](https://user-images.githubusercontent.com/10835611/28897300-ea1e0a8e-7794-11e7-8d3f-1f6bd7566092.png)

**Comment by randyaskin** [comment]
I believe this is related to a known limitation of the `<input type=number>` element in IE, see https://www.polymer-project.org/1.0/docs/devguide/data-binding#native-binding - we could change the spinner demo to use a string instead, which is what we've done in most of our demos.

**Comment by randyaskin** [comment]
Version 2.0.3:
1. Changed demo from `<input type=number>` to `<input type=text>`
2. Fixed actual component sizing in IE by adding `px` to the style attribute
