### ISSUE TITLE
Spinner: Padding off in properties.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#221]
Super minor, but the padding for "size" in properties looks off in both default and hidden tabs.

![screen shot 2017-08-02 at 3 14 08 pm](https://user-images.githubusercontent.com/10835611/28897466-b411b25a-7795-11e7-9c16-7ff81461a8bb.png)

**Comment by katemenkhaus** [comment]
This is not specific to spinner. It is an issue with px-demo

**Comment by katemenkhaus** [comment]
Has been fixed in px-demo. Now all the repos need to be rebuilt to make the change.
