### ISSUE TITLE
popover: Left orientation popover zindex may need an adjustment to be fully visible.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#224]
Right now, the left orientation property will get tucked underneath the nav partially clipping the popover's content.

## Screenshot:

![screen shot 2017-08-02 at 4 51 02 pm](https://user-images.githubusercontent.com/10835611/28900023-11ad8f58-77a3-11e7-9b43-4de51833ae22.png)

**Comment by randyaskin** [comment]
This isn't a z-index problem, it's physically impossible for an iFrame's contents to spill over onto the parent window - they each have their own layering logic. Ben has a separate issue open to enable smart orientation functionality on popover, which could help mitigate this.
