### ISSUE TITLE
Accordion Header - Icon alignement is off

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#225]
The "Open" Chevron and the "Action" Icon sit too low:
- Chevron needs to move up 1 pixel
- "Action" icon needs to move up 2 pixel
![box-image](https://user-images.githubusercontent.com/25111262/28933419-d8b64dcc-7831-11e7-8ec7-f751f0456b4d.png)

**Comment by randyaskin** [comment]
Fixed in v1.0.3.
