### ISSUE TITLE
Make sure footers are uniform across various pages in preidx-ui.com

### ISSUE THREAD

**Issue by mdwragg** [predix-ui/predix-ui.github.io#23]
Seem to be differences in the footers on the static pages vs. the ones from components/css.

**Comment by katemenkhaus** [comment]
This was fixed in v0.2.7
Currently there is an error in the build so it isn't live yet.

**Comment by mdwragg** [comment]
@Menkhaus-ge - can we have a defect to reflect the build issue. Currently we aren't tracking that. Thanks.

**Comment by katemenkhaus** [comment]
open a new defect #37 build is error out with 'Error: spawn E2BIG'

**Comment by runn-vermel** [comment]
fixed in v0.2.9
