### ISSUE TITLE
KPI: Size and spacing doesn't match Key Value Pair

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#230]
We should make them match each other in case they are showing side-by-side. 
- ON the KPI component, the Label is far away from value and the Label font seems to be too big.

**Current: far away**
![box-image-1](https://user-images.githubusercontent.com/25111262/28943028-38e01d8e-7852-11e7-9ad1-e1c0b6fde6fa.png)

**Expected: much closer**
![box-image-2](https://user-images.githubusercontent.com/25111262/28943039-41430220-7852-11e7-965a-36d874cfdc93.png)

**Comment by talimarcus** [comment]
Fixed in https://github.com/PredixDev/px-kpi/commit/933657d9d681cd18f406ae16cae68887d7b72454
