### ISSUE TITLE
Timeline enhanced state: Text sits too high

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#233]
In the enhanced state, the text sits a little high, it should ether be top aligned with the circles or the two lines of text could be vertically center aligned with the circles.

**Something like this:**

![box-image](https://user-images.githubusercontent.com/25111262/28943972-a05dac12-7855-11e7-8386-81f15f9ab30d.png)

**Comment by randyaskin** [comment]
Fixed in v1.0.4.
