### ISSUE TITLE
Data Table: Hover color change on selected sort column state needs to be removed

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#235]
Current:
1. Open data table
2. enable "Sortable"
3. Click on the sortable column. The type turns $select-default.
4. Hover over the type. The type changes color to $select-hover.

Expected:
4. Hover over the type. The type doesn't change color. 

Non sorted, sortable columns keep their hover color change.

**Comment by randyaskin** [comment]
Are you sure about this? The hover effect indicates to the user that clicking on something will have an action. In this case, clicking on an already sorted column header will reverse the sort order, then clicking again will turn off the sort.
