### ISSUE TITLE
Dropdown: Multi-select mode should have standard checkboxes

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#236]
The circles with the checkmarks resemble radio buttons and their behavior is ambiguous. 
Please also remove the counter above the menu and the "X". 

![box-image-1](https://user-images.githubusercontent.com/25111262/28950526-7170488c-7879-11e7-855a-a89c2fa6bdb2.png)

**Comment by randyaskin** [comment]
Adding an actual checkbox greatly complicates the implementation of dropdown, as you have to do all kinds of additional work to bind to the checked state of the checkbox, handle the events when the checkbox is changed, etc. I could switch to a checkmark icon without the circle if that would help - looks like that's another one that Ken forgot to re-create in all the icon confusion.

The event counter is standard for all of our demo pages that include events (see especially the date-time components). And without the X, the users won't know that the default behavior is to provide a clear button for easily de-selecting all the selections. I thought the feedback Justice has been getting is that it's confusing when we have functionality in the API that isn't reflected in the demo.

**Comment by randyaskin** [comment]
Fixed in v4.0.4.
