### ISSUE TITLE
Dark theme doesn't activate when coming from an instructional page

### ISSUE THREAD

**Issue by JusticeRises** [predix-ui/predix-ui.github.io#238]
On all browsers.

When you turn on the dark theme on a page that doesn't posses a dark theme, like any of the design guidelines or getting started pages, and then go to a component or a home page the dark theme is not the one that loads.

Example steps to replicate:

1. Go to https://www.predix-ui.com/#/guidelines/navigation/
2. Turn on dark theme
3. Go to the home page using the side navigation

The light theme will be the one that loads while the slider will state that the dark theme is activated.

--

<img width="1230" alt="screen shot 2017-08-07 at 11 49 00 am" src="https://user-images.githubusercontent.com/5334481/29041196-eeda1754-7b66-11e7-84f9-03948fe80b4a.png">

**Comment by randyaskin** [comment]
It appears someone fixed this, I'm not seeing it today.
