### ISSUE TITLE
404 on px-vis catalog page

### ISSUE THREAD

**Issue by davidrleonard** [predix-ui/predix-ui.github.io#240]
See https://www.predix-ui.com/#/elements/vis/px-vis/px-vis (on the new faster site). There's a 404 for `ge_logo.png`. @Menkhaus-ge can you fix?

![image](https://user-images.githubusercontent.com/6456757/29389186-9cde3a5a-829d-11e7-8f0f-5abd840fda0c.png)

**Comment by katemenkhaus** [comment]
are you still seeing this?
