### ISSUE TITLE
Service worker issues

### ISSUE THREAD

**Issue by mdwragg** [predix-ui/predix-ui.github.io#250]
Hi,

`pages/_guides` and `pages/_guidelines` causing 404s in the service-worker.js defn and causing it to fail to install.

Was going to delete stuff out of the SW but wasn't sure what was needed @davidrleonard ;-)

I hard coded the change in `master` to test it but it'll fail when a re-build happens.

Oh, check out my last few commits, I was commenting out stuff to try to nail down the error, you'll need to revert your service worker update code. Sorry about that!

**Comment by davidrleonard** [comment]
Fixed across a couple commits:

* a36073416131ee0f7cf218de5d27dbbfef14bac4
* bcbc918e9f956b9618cea5d58316252cf65faf04
* 5f16ce89e3694a30549c53d35d383bb465a51497

The most relevant is Fixes doc generation and service worker matching patterns (5f16ce89e3694a30549c53d35d383bb465a51497). Here's the commit that explains what happened:

```
Fixes doc generation and service worker matching patterns


Previously, directories/files in _pages/ that were prefixed with
the '_' symbol (e.g. '_pages/_guides/') were being built and
copied to the 'pages/' output directory. These files were used
to hold content not ready for publication. This is a standard
way of marking things that should not be output into the built
files in static site generators like Jekyll.

After the files were copied to the 'pages/' directory, the service
worker generate gulp task would add those '_' files to the list
for the browser to cache.

Then, those files would NOT get pushed to production because a
gitignore pattern caused them to be ignored when the production
build committed all the files.

This led to the service worker attempting to fetch these files
when they did not exist on production. If a service worker
pre-caching files hits a 404, it bails and cancels registration,
causing a performance hit and users to not get the offline cache.

This commit fixes this bug by ensuring no '_' prefixed files or
directories will be copied from '_pages/' during the build.
```
