### ISSUE TITLE
The side jump navigation overlaps the text when the window size changes

### ISSUE THREAD

**Issue by davidrleonard** [predix-ui/predix-ui.github.io#251]
Browser: Chrome 61 (Mac OSX El Capital 10.11)

Steps to reproduce:
1. Open the [introduction page](https://www.predix-ui.com/#/about/introduction) with your browser at full screen width
2. Drag the browser size and make it narrower until you see the side navigation overlap the text

![image](https://user-images.githubusercontent.com/6456757/29425380-e55c8792-8337-11e7-8890-70fd664315f3.png)

**Comment by katemenkhaus** [comment]
Fixed with commit d016f4b
