### ISSUE TITLE
Bullets missing for some browsers

### ISSUE THREAD

**Issue by davidrleonard** [predix-ui/predix-ui.github.io#253]
Browser: Chrome 61 (Mac OSX El Capitan 10.11)

Steps to reproduce:

1. Open the [Design Starter Kit](https://www.predix-ui.com/#/about/start-designing) page
2. Look at the Third Party Resources section. There are no bullets in the bulleted list.

Expected behavior:

There should be bullets visible beside each `<li>`

![image](https://user-images.githubusercontent.com/6456757/29425599-b2b1d94a-8338-11e7-8ffd-ffb84925babf.png)

**Comment by katemenkhaus** [comment]
The removal of the bullets was on purpose. The designers felt it was less cluttered this way.

**Comment by katemenkhaus** [comment]
Bullets have since been re-added
