### ISSUE TITLE
Component Links should be updated in multiple pages

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#259]
We should update the links to components within the copy of some of the guideline sections  Currently, all of these links to components are landing on the home page.

## Example
**Section: Developing with the system:** Link to px-spinner points to
```<a href="https://www.predix-ui.com/#/modules/px-spinner/" class="style-scope view-about-start-developing">px-spinner</a>```
Should be: 
```https://www.predix-ui.com/#/elements/px-spinner... ```

## List of occurrences
***Section: Developing with the system*** 
px-spinner

***Section: Design Guidelines/navigation*** 
px-app-nav, px-breadcrumbs, px-context-browsers, px-branding-bar, px-tabs

***Section: Design Guidelines/page Layout*** 
px-layout-design, px-spacing, px-flexbox-design, px-widths-responsive-design, px-card

***Section: Design Guidelines/Materiality*** 
color palette

***Section: Design Guidelines/Iconography*** 
px-icon-set

***Section: Design Guidelines/Elevations*** 
px-shadows-design and all components listed under component layering

***Section: Design Guidelines/Mobile*** 
px-appnav, px-context-browser, px-widths-responsive-design, px-table-view

**Comment by randyaskin** [comment]
Should be fixed with the trailing slash fix I put in this afternoon.
