### ISSUE TITLE
Develop with the system:  Portions of Spinner's code snippet in dark theme not legible.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#261]
In https://www.predix-ui.com/#/about/start-developing after switching to dark theme, notice portions of the spinner code snippets are illegible on the dark background.

## Screenshot:

![screen shot 2017-08-18 at 9 50 01 am](https://user-images.githubusercontent.com/10835611/29468824-aa70b752-83fa-11e7-97ad-f8f9a6e65b59.png)

**Comment by katemenkhaus** [comment]
Fixed on aug 23 with commit 5deb706
