### ISSUE TITLE
Safari9:  404's on page layout page.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#263]
Getting 2 404's on safari9 only, when loading https://www.predix-ui.com/#/design/page-layout

## Screenshot:
![screen shot 2017-08-18 at 10 00 24 am](https://user-images.githubusercontent.com/10835611/29469237-3ee6c15a-83fc-11e7-8ae5-07dfc4b74ff3.png)

**Comment by mdwragg** [comment]
Dropped support for Safari 9.x so closing this 👍
