### ISSUE TITLE
Dark theme for guidelines

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#264]
Some guidelines have dark theme and others don't have it.
Opening this issue to track the ones that don't have a dark theme:

1. https://www.predix-ui.com/#/develop/vis/terminology
2. https://www.predix-ui.com/#/develop/vis/configure-charts
3. https://www.predix-ui.com/#/develop/vis/configure-toolbar
4. https://www.predix-ui.com/#/develop/vis/web-workers
5. https://www.predix-ui.com/#/develop/vis/crosshair
6. https://www.predix-ui.com/#/develop/internationalization
7. https://www.predix-ui.com/#/develop/localizable-strings

**Comment by randyaskin** [comment]
All of the vis pages should be done now, and i18n/l10n are done as well. The design guidelines still need to be converted.

**Comment by randyaskin** [comment]
@Menkhaus-ge finished the design guidelines.
