### ISSUE TITLE
Safari9 404'ng all over itself when loading the gallery page.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#265]
404's when loading: https://www.predix-ui.com/#/design/gallery,  in Safari9 only:

![screen shot 2017-08-18 at 10 09 50 am](https://user-images.githubusercontent.com/10835611/29469533-855a2b9e-83fd-11e7-9f1f-a343e217a0f7.png)

**Comment by mdwragg** [comment]
Dropped support for Safari 9.x so closing this 👍
