### ISSUE TITLE
Safari9: Last tutorial in additional resources is not loading at all with typeErrors

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#269]
In https://www.predix-ui.com/#/about/resources, last tutorial Predix Web App Starter Developer Guide is causing errors and not loading in Safari9.

![screen shot 2017-08-18 at 11 01 50 am](https://user-images.githubusercontent.com/10835611/29471380-ad2e0c60-8404-11e7-9286-0d9b4e951698.png)

**Comment by mdwragg** [comment]
Dropped support for Safari 9.x so closing this 👍
