### ISSUE TITLE
Forms Page not responsive.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#271]
https://www.predix-ui.com/#/css/visual/px-forms-design is not responsive, in Chrome, FF, Safari9.
To be more specific, input and inline fields tabs in Forms page seem to have this issue.

# Screenshot:
![screen shot 2017-08-18 at 3 34 19 pm](https://user-images.githubusercontent.com/10835611/29480102-e8c8b114-842a-11e7-8fb2-a293646ada31.png)

**Comment by randyaskin** [comment]
I'm unable to reproduce this. Looks fine in Firefox on my machine. Plus that's the same footer we use on every page... ¯\_(ツ)_/¯

**Comment by ppeyro** [comment]
Neither can I anymore... Will keep an eye out for it, but closing for now.
