### ISSUE TITLE
Cache related Dropdown styling issue.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#272]
Dropdown styling on the new site looks different than the design spec, we should double check.

For example:
- Text color seems to be set to the "disabled" styles, even though the dropdown item is selectable.
- Background color should be $gray1 on hover looks like $gray5.

## Screenshot:
![screen shot 2017-08-18 at 3 49 20 pm](https://user-images.githubusercontent.com/10835611/29480552-ec3e3208-842d-11e7-950e-8b4135dd1bca.png)

**Comment by ppeyro** [comment]
Actually, this seems to be cache related.  If you clear cache and reload the page, the dropdown does have the right styles.  

Leaving this open since clearing cache every time a new page is loaded is not very realistic.

**Comment by nonmetalhail** [comment]
Kate seems to think this is related to dark theme switcher

**Comment by randyaskin** [comment]
A few variables existed in px-dark-theme but not in px-theme for dropdown (and also context browser trigger) so on first load, text would use the fallback of black. Then switching to dark theme would pick up the lighter text color. Switching back to light theme, it wouldn't find the variable *and* wouldn't fall back, so it would just remain in the lighter color. Solved!
