### ISSUE TITLE
Home page:  Rendering issues in IE11.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#275]
Looks like after the latest updates, home page is acting up on IE11 again.

Predix Design System image in hero not rendering.
Also animations are not working; error in console log.

## Screenshots:

![2017-08-21_1657](https://user-images.githubusercontent.com/10835611/29575193-a326ca6a-8718-11e7-932e-000ce83587ec.png)

![2017-08-21_1656](https://user-images.githubusercontent.com/10835611/29575210-abe1498c-8718-11e7-954e-51fe65ea7946.png)

**Comment by katemenkhaus** [comment]
fixed in commit 872befe
