### ISSUE TITLE
toggle-design:  Missing sass doc viewer id in documentation.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#278]
In https://www.predix-ui.com/#/css/visual/px-toggle-design page, looks like the id is not properly rendering in **important things to remember** section of the document.

### Screenshot:
![screen shot 2017-08-22 at 9 58 31 am](https://user-images.githubusercontent.com/10835611/29577594-d99b3b64-8720-11e7-9ede-f7265b799503.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.2.
