### ISSUE TITLE
Switching between light and dark theme transitions slowly in FF.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#279]
When switching between light and dark theme pages, the transition is quite noticeable in FF only. 
It can be slow enough to leave the page mostly blank during the transition.  Other browsers(chrome and Safari9) handle the transition much faster. 

We will address this in the next refactor.

### Screenshot of the transition from dark to light in FF.

![screen shot 2017-08-22 at 10 16 56 am](https://user-images.githubusercontent.com/10835611/29578179-3a47d376-8723-11e7-8f3c-7f091250f267.png)

**Comment by randyaskin** [comment]
@davidrleonard has indicated that there's nothing we can do about this.
