### ISSUE TITLE
px-functions-design:  Fix typos and broken link in the note section.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#281]
In https://www.predix-ui.com/#/css/utilities/px-functions-design page, change **recommended** to **recommend** in title and body of the **_Important note_** section, also change **install** to **installing**.   See Screenshot below.

Also in the same section, predix-UI catalog documentation page link should go to: https://www.predix-ui.com/#/css/utilities/px-defaults-design, currently goes to the home page.

![screen shot 2017-08-22 at 11 53 43 am](https://user-images.githubusercontent.com/10835611/29582457-9e8473a4-8731-11e7-804a-7746537f7ead.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.2.
