### ISSUE TITLE
IE11: toggling the theme is very slow in responding.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#282]
Dark theme toggle in IE11 takes a good 8-10 secs to actually toggle over and refresh the page with the selected theme.  the toggle button looks like it starts to move over, but then it gets stuck for 8-10 secs before it completes the transition to the other side.

There is nothing in the log, it just takes an awfully long time to toggle over.

### Screenshot:
![2017-08-22_1249](https://user-images.githubusercontent.com/10835611/29584614-319dfaaa-8739-11e7-82b5-4410a3168d49.png)

**Comment by randyaskin** [comment]
@davidrleonard has indicated that there's nothing we can do about this.
