### ISSUE TITLE
Typography:  Enable changing to Bold font.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#283]
In https://www.predix-ui.com/#/css/utilities/px-typography-design, the bold option in the dropdown doesn't trigger the change to bold font.  It does add it to the code snippet however, there is no change in font weight in the sample text.

![screen shot 2017-08-22 at 1 59 38 pm](https://user-images.githubusercontent.com/10835611/29587499-0b41a492-8743-11e7-926c-eb36a845fb1c.png)

**Comment by randyaskin** [comment]
Fixed in v2.0.3.
