### ISSUE TITLE
Alert Message: Long message tab/"more" option issues.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#286]
In https://www.predix-ui.com/#/elements/px-alert-message, switching over to the **long message** tab then selecting the **more** option in the **Type** dropdown has styling issues in all browsers.

## Screenshot :

![screen shot 2017-08-22 at 4 41 31 pm](https://user-images.githubusercontent.com/10835611/29592441-d3b87ed6-8758-11e7-8ead-f665e1edc2a0.png)

**Comment by randyaskin** [comment]
"More" is a fundamentally different message type, which is why it has its own configuration tab to illustrate proper usage. I don't see a way around this without hiding the option from the dropdown, making it less obvious to the user that it's even an option.
