### ISSUE TITLE
App-header: Warning on missing method

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#287]
On Page load in chrome and FF https://www.predix-ui.com/#/elements/px-app-header throws a warning.  Safari9 and IE11 browsers are another story as they're still pending the transpiled version.

### Screenshot:
![screen shot 2017-08-23 at 3 01 56 pm](https://user-images.githubusercontent.com/10835611/29640598-75a9734c-8814-11e7-8343-879123e17f35.png)

**Comment by randyaskin** [comment]
I fixed this in px-card last week, it seems to have been picked up in the rebuild now.
