### ISSUE TITLE
Need to mention import of webcomponents-lite.js

### ISSUE THREAD

**Issue by gstroup** [predix-ui/predix-ui.github.io#290]
This intro page is very helpful, but missing one step:
https://www.predix-ui.com/#/about/start-developing

Please add a note that the webcomponentsjs polyfill must be loaded for cross-browser support.  Something like this:
`<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>`
Without that line, polymer components will only work in Chrome.  (until all the other browser makers implement the spec.)

As you can see, some people in the forum have been tripped up by this:
https://forum.predix.io/questions/26836/simplest-polymer-predix-ui-example-working-cross-b.html

**Comment by randyaskin** [comment]
I did that after I saw the question a few days ago:

<img width="752" alt="screen shot 2017-08-24 at 10 52 31 am" src="https://user-images.githubusercontent.com/2130613/29680740-64d31acc-88ba-11e7-93f9-57caf3afab51.png">

**Comment by gstroup** [comment]
OK, I didn't see that a minute ago.  I see it now.  Thanks for adding that!
