### ISSUE TITLE
Accordion demo snippet is duplicated.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#291]
In https://www.predix-ui.com/#/elements/px-accordion, the sample accordion is duplicated even though there should only be one instance.  Note that it's correctly rendered in the codepen(1 accordion), just duplicated in the demo.

![screen shot 2017-08-25 at 10 38 00 am](https://user-images.githubusercontent.com/10835611/29725747-0499c624-8982-11e7-8f11-f5b3eb4ddadc.png)

**Comment by randyaskin** [comment]
It makes more sense to show 2, otherwise the "expand all / collapse all" buttons would be pretty silly. 😛
