### ISSUE TITLE
Is there a way to remove Path from components pages?

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#294]
The new doc pages have the class extends and the path listed underneath that.
Doesn't seem necessary or relevant to have the Path listed specially since it's a relative path.  
Is there a way to remove the path from the doc pages so it's not confusing?

![screen shot 2017-08-28 at 2 35 59 pm](https://user-images.githubusercontent.com/10835611/29795149-d9233748-8bff-11e7-918e-708fffb914c2.png)

**Comment by randyaskin** [comment]
Not really... it comes from the Google iron-doc-element component.
