### ISSUE TITLE
Context Browser: Fix duplicated catalog link & 404's on api.json.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#296]
Should add "trigger" to the second context browser link label.

Also, the documentation for px-context-browser-trigger is not being pulled in, leaving an empty page with a 404 on px-context-browser-trigger-api.json from iron-request.html.

![screen shot 2017-08-29 at 10 04 16 am](https://user-images.githubusercontent.com/10835611/29833822-83fdf170-8ca1-11e7-9c3a-592ba620a460.png)

**Comment by randyaskin** [comment]
The page is loading now, the link should be updated once it rebuilds.
