### ISSUE TITLE
Context Browser: Property Editor for items/selected route is not triggering when selecting the edit button.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#299]
In Context browser demo, selecting the edit button for items/selected route doesn't trigger the property editor to open, like other pages.  No errors in the console log.

Should mention that's the case for both basic and advanced tabs.

![screen shot 2017-08-29 at 1 37 57 pm](https://user-images.githubusercontent.com/10835611/29843085-a5f43104-8cbf-11e7-9f40-4c4f3e4c4159.png)

**Comment by randyaskin** [comment]
Much broader problem - this will actually impact all components that have sub-components that use the code editor.

**Comment by randyaskin** [comment]
Fixed in Context Browser, Data Table, Map and Tree.
