### ISSUE TITLE
Chart-navigator:  Component is not rendering when navigating to the page from the side nav.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#300]
If you navigate to: https://www.predix-ui.com/#/elements/vis/px-vis/px-vis-chart-navigator, the component doesn't render on the page with no errors in console log.

But if you navigate to the page by going to https://www.predix-ui.com/#/elements/vis/px-vis/px-vis first then selecting the chart navigator from the component catalog listed in that page, you'll get the component rendering properly.

### Navigate directly to it from side bar:

![screen shot 2017-08-30 at 2 28 25 pm](https://user-images.githubusercontent.com/10835611/29895954-f307539c-8d8f-11e7-839c-1d69a35d14a3.png)

### Navigate to the chart-navigator by going through the vis catalog first:

![screen shot 2017-08-30 at 2 28 08 pm](https://user-images.githubusercontent.com/10835611/29895982-0db6862c-8d90-11e7-885e-bd562cb225bf.png)

**Comment by katemenkhaus** [comment]
Fix in v3.1.15 of px-vis (commit da89b75)
