### ISSUE TITLE
Suggested text change: Welcome to Predix UI paragraph on Home Page

### ISSUE THREAD

**Issue by Aileen-H** [predix-ui/predix-ui.github.io#31]
Instead of "We've produced Predix UI as a set of user interface components that enable designers and developers to quickly and easily create Industrial Internet web applications that run on top of Predix services and data." 

Consider: "Our user interface components enable you to quickly and easily create Industrial Internet web applications that run on dedicated Predix services and data."

**Comment by runn-vermel** [comment]
fixed.
