### ISSUE TITLE
px-login demo tries to load user-info-sample.json from wrong path

### ISSUE THREAD

**Issue by davidrleonard** [predix-ui/predix-ui.github.io#313]
In Polymer 2.x branch, the px-login demo tries to load user-info-sample.json from `http://localhost:8080/user-info-sample.json` and gets a 404.

Browser: Chrome 64.0.3282.39
OS: OSX Sierra 10.12
Branch: polymer2.0-preview
Commit tested: f1dde34  

![image](https://user-images.githubusercontent.com/6456757/34239975-e0b635cc-e5bf-11e7-99f0-58556665f52c.png)

**Comment by randyaskin** [comment]
It works in the standalone, I suspect the file just needs to be added to extraDependencies in polymer.json of predix-ui.com. Will test that theory.
