### ISSUE TITLE
Code editor doesn't show up for px-vis-timeseries properties

### ISSUE THREAD

**Issue by davidrleonard** [predix-ui/predix-ui.github.io#317]
Steps to reproduce: 

1. Switch to polymer2.0-preview branch and run bower install
2. Open px-vis-timeseries demo (http://localhost:8080/#/elements/vis/px-vis-timeseries)
3. Click the edit button for any properties
4. The code editor doesn't show up

Browser: Chrome 64.0.3282.39
OS: OSX Sierra 10.12
Branch: polymer2.0-preview
Commit tested: f1dde34

**Comment by randyaskin** [comment]
It was missing all its `slot` properties. Should be fixed in v3.3.1.
