### ISSUE TITLE
CSS styling documentation incomplete

### ISSUE THREAD

**Issue by katemenkhaus** [predix-ui/predix-ui.github.io#32]
Some of the component demos are missing the 'styling' section in the api. This is a crucial thing to document with the release of theming. 
example of 'styling' section : 
![screen shot 2017-02-08 at 10 41 40 am](https://cloud.githubusercontent.com/assets/14931112/22751914/47aec64a-edeb-11e6-9b65-a9f21aa0a8c6.png)

list of components that are missing 'styling':
App nav
Vis framework
Vis parallel coordinates
Vis Pie Chart
Vis Polar Chart
Vis Radar Chart
Vis Spark
Vis Timeseries
Vis XY Chart
Calendar Picker
Datetime Field
Datetime Picker
Datetime Range Field
Datetime Range Panel
Rangepicker

**Comment by runn-vermel** [comment]
@Menkhaus-ge - these are missing the styling because HTML minimization was on when this was built. if we simply restart the build, they should build correctly now.

**Comment by katemenkhaus** [comment]
It may be the case with some of these but datetime and vis components don't have the styling documented in the top of the html pages like the other components.

**Comment by runn-vermel** [comment]
yup - they don't have it because cloudflare stripped it out. re-running it should still work.

**Comment by mdwragg** [comment]
Can somebody check what is actually checked in the particular documentation repo e.g. GitHub.com/predix-ui/px-whatever? Cloudflare cannot alter what is built and checked in of course :-)

I think Kate is suggesting the docs are missing from source, I hope not though, pretty sure they all fit added.

**Comment by mdwragg** [comment]
Fit = got, autocorrect...

**Comment by katemenkhaus** [comment]
I clarified with Runn yesterday that I meant for those components listed the styling is not documented in the source files. 
I created this issue more for myself but also if anyone was able to get to it before I could.

**Comment by katemenkhaus** [comment]
App nav
Calendar Picker
Datetime Field
Datetime Picker
Datetime Range Field
Datetime Range Panel
Rangepicker
Now as styling documented.

**Comment by runn-vermel** [comment]
@Menkhaus-ge - can we close this? is it done?

**Comment by katemenkhaus** [comment]
Yes Elliot finished adding them to the vis repos
