### ISSUE TITLE
Link not working to Crosshair Demo from "Developer Guide - Data Visualization - Crosshair"

### ISSUE THREAD

**Issue by Aileen-H** [predix-ui/predix-ui.github.io#324]
![screen shot 2018-01-11 at 3 13 44 pm](https://user-images.githubusercontent.com/21231643/34855371-0f673386-f6f4-11e7-9f3f-cf5578c5cb55.png)
![screen shot 2018-01-11 at 3 13 25 pm](https://user-images.githubusercontent.com/21231643/34855363-01627ca0-f6f4-11e7-8867-91d57fa07b42.png)

**Comment by benoitjchevalier** [comment]
fixed it 👍
