### ISSUE TITLE
Can only see 2.5 alert messages on site home page

### ISSUE THREAD

**Issue by talimarcus** [predix-ui/predix-ui.github.io#327]
## Expected behavior and actual behavior:
When a user takes multiple actions that generate alert messages on our site (e.g. tries navigating to an invalid url multiple times), the third alert message is cut off in the middle, and no further alert messages are shown, though they are added to the DOM.

## Steps to reproduce the problem:
1. Go to predix-ui.com
2. Add some random characters at the end of the url (e.g. `https://www.predix-ui.com/#/homeggg`)
3. Repeat step 2 three more times. The third alert message will be cut off, and the fourth alert message will not show up at all.

## Browser
Chrome 65

## Screenshots:
![screen shot 2018-02-20 at 3 14 24 pm](https://user-images.githubusercontent.com/9092541/36455169-cfb05770-1653-11e8-9ae4-51e31edb3951.png)
![zhhmc](https://user-images.githubusercontent.com/9092541/36455054-5d9e077c-1653-11e8-8c20-177b019de488.png)
![screen shot 2018-02-20 at 3 19 49 pm](https://user-images.githubusercontent.com/9092541/36455188-e7dca808-1653-11e8-811d-76a32f4819b7.png)

**Comment by mdwragg** [comment]
Fixed it. Can you check it again @talimarcus?

**Comment by talimarcus** [comment]
Works for me 👍
