### ISSUE TITLE
Left navigation is able to shrink too much 

### ISSUE THREAD

**Issue by katemenkhaus** [predix-ui/predix-ui.github.io#33]
.side nav should not shrink past 250px wide otherwise, the names start to take up two lines. 

![screen shot 2017-02-08 at 10 54 55 am](https://cloud.githubusercontent.com/assets/14931112/22752513/a7a29570-eded-11e6-9f73-6ab112ebc825.png)

**Comment by runn-vermel** [comment]
fixed with v0.2.6
