### ISSUE TITLE
Homepage links 1 & 2 are dead

### ISSUE THREAD

**Issue by nonmetalhail** [predix-ui/predix-ui.github.io#34]
Links to IO from "1. Setup environment" and "2. Get started" are dead.

![screenshot_2017-02-20-10-35-58](https://cloud.githubusercontent.com/assets/1649404/23137716/66b62bd4-f758-11e6-9402-39c7ac5ce14e.png)

**Comment by runn-vermel** [comment]
fixed in v0.2.6
