### ISSUE TITLE
"What is Predix UI" > seed link doesn't work

### ISSUE THREAD

**Issue by nonmetalhail** [predix-ui/predix-ui.github.io#35]
From "What is Predix UI" the link that reads "Open the Predix UI Seed on Github to see how its built, or to use it right now" doesn't work (at least on Android Chrome). 

I would expect it to take me to the GitHub repo. Instead it takes me to this link, https://www.predix-ui.com/#/external/predix-seed/ which is blank and all sidebar links don't work.

**Comment by runn-vermel** [comment]
fixed in v0.2.6
