### ISSUE TITLE
IE11: In vis 1.0 Demo pages, Properties Edit button doesn't work and is causing null reference error.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#38]
**IE11 special:** 
In predix-ui.com/vis 1.0 charts demo pages(TS, XY, Parallel, Radar and Polar), selecting the edit button doesn't open the edit screen and causes a null reference error.

![2017-03-14_1719](https://cloud.githubusercontent.com/assets/10835611/23928100/0c08ee30-08db-11e7-948d-88a7c9736af9.png)

**Comment by katemenkhaus** [comment]
cannot recreate in redesigned vis demos
