### ISSUE TITLE
IE11: In vis chart pages, getting a script error on page load.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#39]
**IE11 Special:**

In predix-ui.com new vis 1.0 pages cause a script error on load.

![2017-03-14_1714](https://cloud.githubusercontent.com/assets/10835611/23928229/d5fc65d2-08db-11e7-88aa-df98b73c8e49.png)

**Comment by runn-vermel** [comment]
@davidrleonard this is usually caused by "class style" function calls - ie 

functionName() {

instead of functionName: function() {

**Comment by nonmetalhail** [comment]
I dont see this anymore; believe its been resolved.
