### ISSUE TITLE
Slider:  Selecting logarithmic from the scale dropdown causes a Nan Error.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#47]
In the demo page for slider, <_Default Tab_>: if you select logarithmic from the scale dropdown, you'll get a NaN error in the console log.

No error generated if you switch to the <_logarithmic_> tab which has the scale set to logarithmic by default.

### Screenshot:

![screen shot 2017-04-12 at 4 31 46 pm](https://cloud.githubusercontent.com/assets/10835611/24983683/a073e894-1f9d-11e7-83a2-1fea07d132b3.png)

/cc @nonmetalhail

**Comment by randyaskin** [comment]
Doesn't seem to be an issue anymore in the redesign.
