### ISSUE TITLE
Warnings about long running scripts and missing px-theme-style file when loading demo pages.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#48]
Recently noticed a few warnings when loading component demo pages:
1. Missing px-theme-style warnings. 

2. Violations: long running script and handler timestamps.   This one seems to be specific to chrome's canary version 56 which I guess I am a lucky winner of and it can be taken care of by checking off/hide violations.  But just filing this in case others have noticed it too. More details on stackoverflow:
http://stackoverflow.com/questions/41218507/violation-long-running-javascript-task-took-xx-ms

I didn't exhaustively go through all the pages, but noticed these on slider: alert, colors, vis pages, etc...

### Browser: 
Chrome Version 56.0.2924.87 (64-bit)

### Missing px-theme-styles Screenshot:
![screen shot 2017-04-12 at 4 43 40 pm](https://cloud.githubusercontent.com/assets/10835611/24984053/ed08d6e0-1f9f-11e7-816f-6a2ebd7128f7.png)

### Long running script Violation Screenshot:

![screen shot 2017-04-12 at 4 36 01 pm](https://cloud.githubusercontent.com/assets/10835611/24983777/57cbde8e-1f9e-11e7-91c9-111226929343.png)

/cc @runn-vermel

**Comment by randyaskin** [comment]
We've been fixing the missing style errors one-by-one. I haven't seen the long running script errors at all in our testing post-redesign.
