### ISSUE TITLE
Slider:  Typo in description

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#49]
In the description section of slider, there is a typo that should be fixed.

**isRnage** should be changed to **isRange**. 

Screenshot:

![screen shot 2017-04-12 at 5 02 45 pm](https://cloud.githubusercontent.com/assets/10835611/24984398/f26041f8-1fa1-11e7-9cba-866f1c90f24c.png)

/cc @nonmetalhail

**Comment by talimarcus** [comment]
Fixing this

**Comment by talimarcus** [comment]
Actually looks like this has already been fixed
