### ISSUE TITLE
Footer: GE Logo color in page footer looks wrong in safari9 only.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#51]
Looks like it's overlaid?
Screenshot:

![ge_logo_safari9](https://cloud.githubusercontent.com/assets/10835611/25967197/2a8fe374-3642-11e7-8efd-25426ef0ac1c.png)

**Comment by randyaskin** [comment]
Fixed the gamma channel on monogram-wdmk.png in px-demo, which is used by everything else. This change will get picked up by the demo site and each repository as its demo rebuilds (probably too minor to warrant Runnbotting).
