### ISSUE TITLE
normalize: getting a 404 on sassdoc.json.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#53]
Getting a 404 on page load. Here's the screenshot:
![screen shot 2017-05-11 at 3 07 17 pm](https://cloud.githubusercontent.com/assets/10835611/25974074/d58c87b4-365b-11e7-9f93-4f65046129c5.png)

**Comment by benoitjchevalier** [comment]
fixed in nornmalize 1.0.1
