### ISSUE TITLE
Sidebar doesnt scroll to bottom

### ISSUE THREAD

**Issue by nonmetalhail** [predix-ui/predix-ui.github.io#57]
Scroll all the way down and cannot see final item... 

<img width="366" alt="screen shot 2017-05-31 at 4 42 54 am" src="https://cloud.githubusercontent.com/assets/1649404/26630500/cd7932ec-45bb-11e7-9a23-b930b9fcb465.png">

**Comment by benoitjchevalier** [comment]
fixed
