### ISSUE TITLE
Polar Chart: 404'ng on typeahead.html

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#59]
Getting a 404 when loading polar chart on predix-ui.com.

**Screenshot:**

![screen shot 2017-06-01 at 5 39 14 pm](https://cloud.githubusercontent.com/assets/10835611/26706345/7f6a179c-46f1-11e7-80b9-93a48c2c3dbd.png)

**Comment by nonmetalhail** [comment]
Cannot recreate, but do see a different 404, which I'm fixing

**Comment by nonmetalhail** [comment]
Fixed
