### ISSUE TITLE
Redesign/px-tree: demo is not working in IE11 and Safari9

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#63]
Redesign: px-tree demo doesn't load on IE11 and safari9.
Getting a script error: "expected ; "expected identifier"   

### IE11
![2017-07-25_1002](https://user-images.githubusercontent.com/10835611/28584160-8e2a9ff0-7120-11e7-87f8-6c0946bf17e7.png)

### Safari9:
![screen shot 2017-07-28 at 10 46 25 am](https://user-images.githubusercontent.com/10835611/28729768-70eac064-7382-11e7-9dde-f0a2ba96ae39.png)

**Comment by davidrleonard** [comment]
Fixed
