### ISSUE TITLE
Side Nav:  Can't scroll all the way down to the component list in Firefox.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#65]
This is only in Firefox browser.

Couple of notes:

- Side nav's scroll bar doesn't scroll all the way down the component list so no way to reach the last 5 components (tooltip, tree, ...)

- "Tree" seems to be missing after "Tooltip". Screenshot below.

### Side Nav scrollbar cutoff:
![screen shot 2017-07-28 at 10 37 47 am](https://user-images.githubusercontent.com/10835611/28729367-19f717d6-7381-11e7-8abb-d0a5081bf173.png)

### Tree missing from the list:
![screen shot 2017-07-28 at 10 43 02 am](https://user-images.githubusercontent.com/10835611/28729589-d0499338-7381-11e7-9624-a89fb79a16b5.png)

**Comment by benoitjchevalier** [comment]
Fixed
