### ISSUE TITLE
px-actionale-text-icons-design:  Missing actionable text icon

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#68]
Icon missing in actionable text:

## Screenshot Redesign:

![screen shot 2017-07-28 at 12 35 00 pm](https://user-images.githubusercontent.com/10835611/28733575-a3924118-7391-11e7-8c25-f73d74333e66.png)

## Screenshot Archived page:
![screen shot 2017-07-28 at 12 37 14 pm](https://user-images.githubusercontent.com/10835611/28733553-8d0c6306-7391-11e7-8b78-bea955cdaefc.png)

## Environment:
Browser: Chrome

**Comment by talimarcus** [comment]
I'm working on this one (can't assign myself)

**Comment by talimarcus** [comment]
Closed: https://github.com/PredixDev/px-actionable-design/commit/665dbab1ba8b8aa0746afb33d236fb38e69d02c7
