### ISSUE TITLE
px-button-group-design:  Disabled toggle is on by default, should be off by default.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#69]
px-button-group-design:  Disabled toggle is on page load. It should be off since the buttons are not disabled.

## Screenshot:
![screen shot 2017-07-28 at 12 39 53 pm](https://user-images.githubusercontent.com/10835611/28733682-1986f706-7392-11e7-889d-c22d29c4f402.png)

## Environment:
Browser: Chrome

**Comment by benoitjchevalier** [comment]
fixed in buttons-design 2.0.1
