### ISSUE TITLE
px-button-group-design:  404's on safari9 and FF.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#70]
Getting 404's on page load, but only in safari9 and FF:
Chrome and IE11 seem fine.

## Screenshot
![screen shot 2017-07-28 at 12 44 19 pm](https://user-images.githubusercontent.com/10835611/28733862-eb336db6-7392-11e7-9f1c-85f3f11a0a5e.png)

## Environment:
Browsers: Safari9 & FF

**Comment by benoitjchevalier** [comment]
badges slow to load altely
