### ISSUE TITLE
px-Buttons-design: warnings when loading the page in safari9, IE11 and FF.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#72]
Warning about malformed code on page load only in safari9, IE11 and FF.
Chrome seems fine.

## Screenshot:

![screen shot 2017-07-28 at 1 00 33 pm](https://user-images.githubusercontent.com/10835611/28734334-4e6652e8-7395-11e7-928c-ede335f31c6f.png)

**Comment by benoitjchevalier** [comment]
can't reproduce
