### ISSUE TITLE
px-forms-design: malformed code/lang undefined warning on page load.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#73]
Warning about malformed code on page load in all browsers.

#Screenshot: 
![screen shot 2017-07-28 at 1 10 39 pm](https://user-images.githubusercontent.com/10835611/28734528-3527cd42-7396-11e7-8864-5eed00868c4c.png)

**Comment by randyaskin** [comment]
Added a check in px-sass-doc. Once forms-design rebuilds, this warning should go away.
