### ISSUE TITLE
px-dropdown: right positioning is off when inspector is open.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#74]
Px-dropdown's panel right positioning seems to be off. It opens up way off to the side.

# Screenshot:
![screen shot 2017-07-28 at 1 25 49 pm](https://user-images.githubusercontent.com/10835611/28735076-8d533432-7398-11e7-82e4-2eeb1bc0b3c4.png)

## Environment:
Browsers: All

**Comment by benoitjchevalier** [comment]
Moved to dropdown: https://github.com/PredixDev/px-dropdown/issues/55
