### ISSUE TITLE
Toggles Gone Wild: They revert back to the old toggle in safari9, FF  & IE11 at random.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#76]
Toggles reverted back to the old toggles even after multiple cache clearing.
Noticed in Safari9, FF and IE11 only.  Chrome and FF seem to happily stick with the right toggle.

### FF fine at first, Safari9 gets the old style toggles:
![screen shot 2017-07-28 at 2 33 00 pm](https://user-images.githubusercontent.com/10835611/28737393-23d10ec0-73a3-11e7-8d9b-59e99e33dcd6.png)

### FF reverted back too:
![screen shot 2017-07-28 at 2 39 48 pm](https://user-images.githubusercontent.com/10835611/28737402-2abcda8e-73a3-11e7-81a2-6ef001510298.png)

**Comment by benoitjchevalier** [comment]
Old demos get served somehow. Probably caching issue, should go away during the week-end
