### ISSUE TITLE
Placeholder text in typeahead too faint in FF.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#77]
Placeholder text in typeahead "Type in a search term...", too faint to be visible.

## Screenshot:

![screen shot 2017-07-28 at 2 55 10 pm](https://user-images.githubusercontent.com/10835611/28737806-1ad319a6-73a5-11e7-87d4-11a31dd2abc7.png)

## Environment:
Browser: FF 54

**Comment by benoitjchevalier** [comment]
I've actually seen that on and off on chrome as well, maybe some timing on loading the theme?

**Comment by nonmetalhail** [comment]
will look into this

**Comment by nonmetalhail** [comment]
General error in forms design + dark theme needed to be applied to sidebar. Fixed.
