### ISSUE TITLE
Flexbox: Flex Container examples don't render properly in IE11

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#78]
IE11: Totally random content (Login screen?)  instead of the codepe.  This is happening in Examples section: "Basic Flex Container" and "...container with directions".

### IE11
![2017-07-28_1505](https://user-images.githubusercontent.com/10835611/28738124-917337f2-73a6-11e7-93e0-217a9ed67b8f.png)

### Chrome
![screen shot 2017-07-28 at 3 10 04 pm](https://user-images.githubusercontent.com/10835611/28738191-e4737098-73a6-11e7-9d43-f113423c1714.png)

### IE11 console log full of goodies:
![2017-07-28_1516](https://user-images.githubusercontent.com/10835611/28738398-1e89b200-73a8-11e7-9e41-472b53657954.png)

**Comment by benoitjchevalier** [comment]
Removed the codepens in there, looking fine now
