### ISSUE TITLE
flexbox-design:  webcomponents-lite.js 404's on page load.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#79]
404's on Chrome and Safari9.

## Screenshot:
![screen shot 2017-07-28 at 3 12 11 pm](https://user-images.githubusercontent.com/10835611/28738374-f01ecc7a-73a7-11e7-9ab5-f88551a077d8.png)

**Comment by benoitjchevalier** [comment]
fixed in flexbox 1.01
