### ISSUE TITLE
normalize-design: 404 on sassdoc.json

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#81]
![screen shot 2017-07-28 at 3 43 07 pm](https://user-images.githubusercontent.com/10835611/28738941-840ea7f4-73ab-11e7-96a2-c832227c4318.png)

**Comment by nonmetalhail** [comment]
I do not see this error

**Comment by benoitjchevalier** [comment]
I think I fixed this....
