### ISSUE TITLE
Following all the Links in footer timesout without redirecting.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#83]
Not sure if this is because we're in dev mode, but filing this so we can track it down next week.
Selecting any of the links in the footer causes a time out.

## Screenshot:
![screen shot 2017-07-28 at 4 53 43 pm](https://user-images.githubusercontent.com/10835611/28740089-a60d8f78-73b5-11e7-8dfb-fa0ddf9604c3.png)

## Environment:
Browsers: Chrome, FF (so far)

**Comment by nonmetalhail** [comment]
I cannot recreate this. Leagal and Contact Us links work fine. There is an error if you click on the logo which should redirect to ge.com/digital. Looking into that

**Comment by nonmetalhail** [comment]
Made a fix to px-demo-footer. Should get picked up next time site/demos build
