### ISSUE TITLE
Alert Label:  Toggling to badge doesn't fit the alert label.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#85]
Alert label won't fit in the badge if you are in important label tab and turn the toggle to on.

## Screenshot:
![screen shot 2017-07-28 at 5 29 20 pm](https://user-images.githubusercontent.com/10835611/28740530-9ea3a7c2-73ba-11e7-885c-776272a16847.png)

### More visible in dark theme:
![screen shot 2017-07-28 at 5 35 18 pm](https://user-images.githubusercontent.com/10835611/28740573-36baa0ba-73bb-11e7-83e6-523822f508f9.png)

**Comment by randyaskin** [comment]
Mitigated in v2.0.3 of px-alert-label. Disabled the toggle and added help text.
