### ISSUE TITLE
app-header & px-breadcrumbs:  Need transpiled version for browsers other than chrome.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#87]
app-header is not working in any other browsers except chrome currently.

### Safari9
![screen shot 2017-07-28 at 5 52 31 pm](https://user-images.githubusercontent.com/10835611/28740749-912c90e2-73bd-11e7-89d6-818981807521.png)

### FF

![screen shot 2017-07-28 at 5 52 53 pm](https://user-images.githubusercontent.com/10835611/28740753-a357750c-73bd-11e7-8d69-c5f51abe7dce.png)

**Comment by ppeyro** [comment]
Updating this.  As of today, px-breadcrumbs loads in every browser except safari9. Opened a separate issue for tracking breadcrumbs demo in Safari, so removing breadcrumbs from this issue.

**Comment by mdwragg** [comment]
@davidrleonard, do you want me to look at this?

**Comment by davidrleonard** [comment]
Breadcrumbs is fixed, we're holding off on app-header, collapsing into one bug for that one #143.
