### ISSUE TITLE
Branding Bar:  Custom Header tab, properties not working and warning in codepen.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#89]
Issue1:  Custom Header tab, selecting to change the app title in properties doesn't seem to work.
Issue2: Getting a warning about px-theme  missing in codepen.

### Custom Header Tab:
![screen shot 2017-07-31 at 10 04 26 am](https://user-images.githubusercontent.com/10835611/28788962-fae4306e-75d7-11e7-8799-bfc978dacfca.png)

### Warning in codepen:

![screen shot 2017-07-31 at 10 02 11 am](https://user-images.githubusercontent.com/10835611/28789009-2a8c9e64-75d8-11e7-8493-c05310c8072a.png)

## Environment:
Browser: Chrome

**Comment by randyaskin** [comment]
Closed the first part in v1.0.3 of px-branding-bar. I believe that CodePen always throws that error in the second image, it doesn't seem to matter.
