### ISSUE TITLE
IE11: images not rendering on home page

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#91]
Two images on the home page are not rendering in IE11:

sketch-stencil.png
using_the_system.png

## Screenshot:

![2017-07-31_1046](https://user-images.githubusercontent.com/10835611/28790477-12a39130-75de-11e7-81b3-e90b55c6ca9e.png)

**Comment by mdwragg** [comment]
fixed by 6dc06fc67164abad87aaceab693acbb4c4828727
