### ISSUE TITLE
Breadcrumbs: Safari9 errors on demo load.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#92]
Breadcrumbs demo loads fine in every browser except Safari9.

## Screenshot:

![screen shot 2017-07-31 at 10 56 30 am](https://user-images.githubusercontent.com/10835611/28790690-ede198aa-75de-11e7-85e9-01a06646a787.png)

**Comment by davidrleonard** [comment]
Fixed
