### ISSUE TITLE
px-deck-selector: Add Dashboard option in the demo doesn't seem to work.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#95]
Tried adding a deck in basic tab by selecting "add dashboard" from the dropdown.  
Assumed this is supposed to add another deck to the list of decks but it doesn't.  Unclear if the intention was to show how adding a deck might be possible in the first place and if this is an actual bug in the demo/component? 
No errors in log.  Also, checked the pre-refresh component and it doesn't work on that either.

## Screenshot:

![screen shot 2017-07-31 at 11 23 13 am](https://user-images.githubusercontent.com/10835611/28792000-1c6baf40-75e3-11e7-973f-d9eb08d41462.png)

**Comment by talimarcus** [comment]
I'll look at this

**Comment by talimarcus** [comment]
This is working fine -- it fires the event as expected (based on the documentation), and it's up to the developer to listen for that event and do something with it (like allow the user to "Add Dashboard").

When we have a chance to come back to this, it might be worth adding a counter/message saying which event has been fired (similar to what we do with the datetime components) so someone playing around with this can better understand what is happening.
