### ISSUE TITLE
Context Browser: demo fails to load in IE11 and Safari9,  missing the transpiled version? 

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#97]
No joy loading the context browser in safari9 or IE11.  
Chrome and FF seem fine.

### IE11
![2017-07-31_1207](https://user-images.githubusercontent.com/10835611/28793782-037846fa-75e9-11e7-9f30-c6808f711d79.png)

### Safari9:
![screen shot 2017-07-31 at 12 09 11 pm](https://user-images.githubusercontent.com/10835611/28793815-1c5549b6-75e9-11e7-9be1-aad43196d222.png)

**Comment by davidrleonard** [comment]
Fixed with transpilation.

**Comment by davidrleonard** [comment]
Fixed
