### ISSUE TITLE
Context Browser: Dark theme is missing.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#98]
Seems the theme files might be loading partially?  Possibly, missing demo-dark-theme.html?

## Screenshot:
![screen shot 2017-07-31 at 12 14 32 pm](https://user-images.githubusercontent.com/10835611/28794081-f25dcb32-75e9-11e7-81b4-e91622cc5274.png)

## Browsers:
Chrome and FF

**Comment by randyaskin** [comment]
Fixed in v2.0.1.
