### ISSUE TITLE
Context-browser: Should fix Issues with the demo.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#99]
Looks like the advanced tab demo has glitches.

1. In Basic tab:  Based on "items", when you navigate to Assets childre, there should be 2 children, but currently just get an in-progress and returns after the load timeout expires with no children getting loaded.  

2. In Advanced Tab: Similar to issue 1.  Based on the items provided, when you navigate to Alerts children, you should have Alert#1-Alert#4 listed, but it currently just gets an in progress bar and returns after the load timeout expires.  Strangely enough, viewing the children for Assets item works fine.  

3. When collapsed (set collapseat to a bigger value), the context browser seems to just overlay the demo page instead of going into collapsed mode?

4. If you select collapsed in the properties, doesn't seem to actually turn the browser into collapsed mode?

5. We should also enhance the demo to show the actual asset info when selected, right now nothing happens when you select an asset.

## Screenshots:
![screen shot 2017-07-31 at 12 50 57 pm](https://user-images.githubusercontent.com/10835611/28795523-0e5d0e10-75ef-11e7-8b54-5998a9269748.png)

![screen shot 2017-07-31 at 12 46 08 pm](https://user-images.githubusercontent.com/10835611/28795530-13c80634-75ef-11e7-8cb5-52e6e17be761.png)

![screen shot 2017-07-31 at 12 52 25 pm](https://user-images.githubusercontent.com/10835611/28795610-5b939276-75ef-11e7-9ab4-d104317468b9.png)

**Comment by talimarcus** [comment]
Looking at this.

**Comment by talimarcus** [comment]
1. Not able to replicate this one. The Asset children are showing up fine for me.

2. Filed a bug for this in Context Browser, going to update the demo to hide this issue until it's fixed. https://github.com/PredixDev/px-context-browser/issues/79

3. I think this is actually behaving correctly. From what I understand, collapsed mode is for use on mobile screens, and is not really intended to be collapsed at 1500px (though it is possible) and that might be why it looks weird to you. But I might be misunderstanding the issue. The dark overlay is also missing, if that's what you mean @ppeyro?

4. Good catch, fixed now.

5. Working on enhancing the demo

**Comment by ppeyro** [comment]
Sorry Tali, #1 is bogus... I got my notes confused...  Please ignore.

**Comment by talimarcus** [comment]
#5 addressed in this PR.

Working on adding the dark overlay for #3 now.
